local rootPart, attachment, weld, joint, head_2, headMotor6d, nameTagOverride, head_3, headMotor6d_2, weld_2, head_4, headMotor6d_3, weld_3, humanoidRootPart, leftLowerArm, leftLowerArmMotor6d, leftLowerArm_2, leftLowerArmMotor6d_2, weld_4, leftLowerArm_3, leftLowerArmMotor6d_3, weld_5, upperTorso, upperTorsoMotor6d, upperTorso_2, upperTorsoMotor6d_2, weld_6, torso_2, torsoMotor6d, weld_7, rightHand, rightHandMotor6d, rightHand_2, rightHandMotor6d_2, weld_8, rightHand_3, rightHandMotor6d_3, weld_9, rightUpperrArm, rightUpperrArmMotor6d, rightUpperrArm_2, rightUpperrArmMotor6d_2, weld_10, rightUpperArm, rightUpperArmMotor6d, weld_11, leftHand, leftHandMotor6d, leftHand_2, leftHandMotor6d_2, weld_12, leftHand_3, leftHandMotor6d_3, weld_13, leftUpperArm, leftUpperArmMotor6d, leftUpperArm_2, leftUpperArmMotor6d_2, weld_14, leftUpperArm_3, leftUpperArmMotor6d_3, weld_15, rightLowerArm, rightLowerArmMotor6d, rightLowerArm_2, rightLowerArmMotor6d_2, weld_16, rightLowerArm_3, rightLowerArmMotor6d_3, weld_17

local ghastlyGlow = Instance.new("Model")
ghastlyGlow.Name = "GhastlyGlow"
do
	local animSaves = Instance.new("ObjectValue")
	animSaves.Name = "AnimSaves"
	animSaves.Parent = ghastlyGlow
	local config = Instance.new("Configuration")
	config.Name = "Config"
	do
		local normalTexture = Instance.new("Decal")
		normalTexture.Name = "NormalTexture"
		normalTexture.Texture = "rbxassetid://130099326342245"
		normalTexture.Parent = config
		local hurtTexture = Instance.new("Decal")
		hurtTexture.Name = "HurtTexture"
		hurtTexture.Texture = "rbxassetid://87138482960611"
		hurtTexture.Parent = config
		local blinkTexture = Instance.new("Decal")
		blinkTexture.Name = "BlinkTexture"
		blinkTexture.Texture = "rbxassetid://74551710989470"
		blinkTexture.Parent = config
	end
	config.Parent = ghastlyGlow
	local humanoid = Instance.new("Humanoid")
	humanoid.HipHeight = 2
	humanoid.NameDisplayDistance = 0
	humanoid.HealthDisplayType = Enum.HumanoidHealthDisplayType.AlwaysOff
	do
		local animator = Instance.new("Animator")
		animator.Parent = humanoid
	end
	humanoid.Parent = ghastlyGlow
	local stats = Instance.new("Folder")
	stats.Name = "Stats"
	do
		local holdingSprint = Instance.new("BoolValue")
		holdingSprint.Name = "HoldingSprint"
		holdingSprint.Parent = stats
		local sprinting = Instance.new("BoolValue")
		sprinting.Name = "Sprinting"
		sprinting.Parent = stats
	end
	stats.Parent = ghastlyGlow
	local initialPoses = Instance.new("Folder")
	initialPoses.Name = "InitialPoses"
	do
		local rootComposited = Instance.new("CFrameValue")
		rootComposited.Name = "root_Composited"
		rootComposited.Value = CFrame.new(Vector3.new(0, 2.2035, -0.0029)) * CFrame.fromEulerAnglesXYZ(math.rad(86.439), math.rad(-90), 0)
		rootComposited.Parent = initialPoses
		local rootOriginal = Instance.new("CFrameValue")
		rootOriginal.Name = "root_Original"
		rootOriginal.Value = CFrame.new(Vector3.new(0, 2.2035, 0.0028)) * CFrame.fromEulerAnglesXYZ(math.rad(-86.4391), math.rad(90), 0)
		rootOriginal.Parent = initialPoses
		local rootInitial = Instance.new("CFrameValue")
		rootInitial.Name = "root_Initial"
		rootInitial.Value = CFrame.new(Vector3.new(0, 2.2035, 0.0028)) * CFrame.fromEulerAnglesXYZ(math.rad(-86.4391), math.rad(90), 0)
		rootInitial.Parent = initialPoses
		local torsoComposited = Instance.new("CFrameValue")
		torsoComposited.Name = "torso_Composited"
		torsoComposited.Value = CFrame.new(Vector3.new(0, 2.468, -0.0211)) * CFrame.fromEulerAnglesXYZ(math.rad(90), math.rad(-90), 0)
		torsoComposited.Parent = initialPoses
		local torsoOriginal = Instance.new("CFrameValue")
		torsoOriginal.Name = "torso_Original"
		torsoOriginal.Value = CFrame.new(Vector3.new(-0.2652, -0.0018, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(-3.5567))
		torsoOriginal.Parent = initialPoses
		local torsoInitial = Instance.new("CFrameValue")
		torsoInitial.Name = "torso_Initial"
		torsoInitial.Value = CFrame.new(Vector3.new(-0.2652, -0.0018, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(-3.5567))
		torsoInitial.Parent = initialPoses
		local chestComposited = Instance.new("CFrameValue")
		chestComposited.Name = "chest_Composited"
		chestComposited.Value = CFrame.new(Vector3.new(0, 2.9046, -0.0211)) * CFrame.fromEulerAnglesXYZ(math.rad(87.5478), math.rad(-90), 0)
		chestComposited.Parent = initialPoses
		local chestOriginal = Instance.new("CFrameValue")
		chestOriginal.Name = "chest_Original"
		chestOriginal.Value = CFrame.new(Vector3.new(-0.4367, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(2.4533))
		chestOriginal.Parent = initialPoses
		local chestInitial = Instance.new("CFrameValue")
		chestInitial.Name = "chest_Initial"
		chestInitial.Value = CFrame.new(Vector3.new(-0.4367, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(2.4533))
		chestInitial.Parent = initialPoses
		local headComposited = Instance.new("CFrameValue")
		headComposited.Name = "head_Composited"
		headComposited.Value = CFrame.new(Vector3.new(0, 3.3564, -0.0594)) * CFrame.fromEulerAnglesXYZ(math.rad(87.5478), math.rad(-90), 0)
		headComposited.Parent = initialPoses
		local headOriginal = Instance.new("CFrameValue")
		headOriginal.Name = "head_Original"
		headOriginal.Value = CFrame.new(Vector3.new(-0.453, -0.019, 0))
		headOriginal.Parent = initialPoses
		local headInitial = Instance.new("CFrameValue")
		headInitial.Name = "head_Initial"
		headInitial.Value = CFrame.new(Vector3.new(-0.453, -0.019, 0))
		headInitial.Parent = initialPoses
		local hair1Composited = Instance.new("CFrameValue")
		hair1Composited.Name = "hair1_Composited"
		hair1Composited.Value = CFrame.new(Vector3.new(0, 3.0137, 0.7758)) * CFrame.fromEulerAnglesXYZ(math.rad(-3.9597), 0, math.rad(90.0015))
		hair1Composited.Parent = initialPoses
		local hair1Original = Instance.new("CFrameValue")
		hair1Original.Name = "hair1_Original"
		hair1Original.Value = CFrame.new(Vector3.new(0.3781, 0.8197, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-89.9959), math.rad(-1.5039), math.rad(-180))
		hair1Original.Parent = initialPoses
		local hair1Initial = Instance.new("CFrameValue")
		hair1Initial.Name = "hair1_Initial"
		hair1Initial.Value = CFrame.new(Vector3.new(0.3781, 0.8197, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-89.9959), math.rad(-1.5039), math.rad(-180))
		hair1Initial.Parent = initialPoses
		local hair2Composited = Instance.new("CFrameValue")
		hair2Composited.Name = "hair2_Composited"
		hair2Composited.Value = CFrame.new(Vector3.new(0, 2.0011, 0.8459)) * CFrame.fromEulerAnglesXYZ(math.rad(-40.5341), math.rad(0.0017), math.rad(89.9953))
		hair2Composited.Parent = initialPoses
		local hair2Original = Instance.new("CFrameValue")
		hair2Original.Name = "hair2_Original"
		hair2Original.Value = CFrame.new(Vector3.new(-1.015, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, math.rad(36.5744), 0)
		hair2Original.Parent = initialPoses
		local hair2Initial = Instance.new("CFrameValue")
		hair2Initial.Name = "hair2_Initial"
		hair2Initial.Value = CFrame.new(Vector3.new(-1.015, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, math.rad(36.5744), 0)
		hair2Initial.Parent = initialPoses
		local hair3Composited = Instance.new("CFrameValue")
		hair3Composited.Name = "hair3_Composited"
		hair3Composited.Value = CFrame.new(Vector3.new(0, 1.4637, 1.3055)) * CFrame.fromEulerAnglesXYZ(math.rad(-102.7823), 0, math.rad(90))
		hair3Composited.Parent = initialPoses
		local hair3Original = Instance.new("CFrameValue")
		hair3Original.Name = "hair3_Original"
		hair3Original.Value = CFrame.new(Vector3.new(-0.7072, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, math.rad(62.2485), 0)
		hair3Original.Parent = initialPoses
		local hair3Initial = Instance.new("CFrameValue")
		hair3Initial.Name = "hair3_Initial"
		hair3Initial.Value = CFrame.new(Vector3.new(-0.7072, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, math.rad(62.2485), 0)
		hair3Initial.Parent = initialPoses
		local hair4Composited = Instance.new("CFrameValue")
		hair4Composited.Name = "hair4_Composited"
		hair4Composited.Value = CFrame.new(Vector3.new(0, 1.635, 2.061)) * CFrame.fromEulerAnglesXYZ(math.rad(-102.7823), 0, math.rad(90))
		hair4Composited.Parent = initialPoses
		local hair4Original = Instance.new("CFrameValue")
		hair4Original.Name = "hair4_Original"
		hair4Original.Value = CFrame.new(Vector3.new(-0.7748, 0, 0))
		hair4Original.Parent = initialPoses
		local hair4Initial = Instance.new("CFrameValue")
		hair4Initial.Name = "hair4_Initial"
		hair4Initial.Value = CFrame.new(Vector3.new(-0.7748, 0, 0))
		hair4Initial.Parent = initialPoses
		local lArmComposited = Instance.new("CFrameValue")
		lArmComposited.Name = "L_arm_Composited"
		lArmComposited.Value = CFrame.new(Vector3.new(-0.3689, 3.1303, -0.0352))
		lArmComposited.Parent = initialPoses
		local lArmOriginal = Instance.new("CFrameValue")
		lArmOriginal.Name = "L_arm_Original"
		lArmOriginal.Value = CFrame.new(Vector3.new(-0.2261, -0.0045, 0.3688)) * CFrame.fromEulerAnglesXYZ(math.rad(-90.0013), math.rad(2.4521), math.rad(90.0012))
		lArmOriginal.Parent = initialPoses
		local lArmInitial = Instance.new("CFrameValue")
		lArmInitial.Name = "L_arm_Initial"
		lArmInitial.Value = CFrame.new(Vector3.new(-0.2261, -0.0045, 0.3688)) * CFrame.fromEulerAnglesXYZ(math.rad(-90.0013), math.rad(2.4521), math.rad(90.0012))
		lArmInitial.Parent = initialPoses
		local lElbowComposited = Instance.new("CFrameValue")
		lElbowComposited.Name = "L_elbow_Composited"
		lElbowComposited.Value = CFrame.new(Vector3.new(-0.9391, 3.1303, -0.0352))
		lElbowComposited.Parent = initialPoses
		local lElbowOriginal = Instance.new("CFrameValue")
		lElbowOriginal.Name = "L_elbow_Original"
		lElbowOriginal.Value = CFrame.new(Vector3.xAxis * -0.5703)
		lElbowOriginal.Parent = initialPoses
		local lElbowInitial = Instance.new("CFrameValue")
		lElbowInitial.Name = "L_elbow_Initial"
		lElbowInitial.Value = CFrame.new(Vector3.xAxis * -0.5703)
		lElbowInitial.Parent = initialPoses
		local lHandComposited = Instance.new("CFrameValue")
		lHandComposited.Name = "L_hand_Composited"
		lHandComposited.Value = CFrame.new(Vector3.new(-1.4491, 3.1303, -0.0352))
		lHandComposited.Parent = initialPoses
		local lHandOriginal = Instance.new("CFrameValue")
		lHandOriginal.Name = "L_hand_Original"
		lHandOriginal.Value = CFrame.new(Vector3.xAxis * -0.51)
		lHandOriginal.Parent = initialPoses
		local lHandInitial = Instance.new("CFrameValue")
		lHandInitial.Name = "L_hand_Initial"
		lHandInitial.Value = CFrame.new(Vector3.xAxis * -0.51)
		lHandInitial.Parent = initialPoses
		local lFingerComposited = Instance.new("CFrameValue")
		lFingerComposited.Name = "L_finger_Composited"
		lFingerComposited.Value = CFrame.new(Vector3.new(-1.9013, 3.1303, -0.0352))
		lFingerComposited.Parent = initialPoses
		local lFingerOriginal = Instance.new("CFrameValue")
		lFingerOriginal.Name = "L_finger_Original"
		lFingerOriginal.Value = CFrame.new(Vector3.xAxis * -0.4523)
		lFingerOriginal.Parent = initialPoses
		local lFingerInitial = Instance.new("CFrameValue")
		lFingerInitial.Name = "L_finger_Initial"
		lFingerInitial.Value = CFrame.new(Vector3.xAxis * -0.4523)
		lFingerInitial.Parent = initialPoses
		local rArmComposited = Instance.new("CFrameValue")
		rArmComposited.Name = "R_arm_Composited"
		rArmComposited.Value = CFrame.new(Vector3.new(0.3682, 3.1303, -0.0352)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		rArmComposited.Parent = initialPoses
		local rArmOriginal = Instance.new("CFrameValue")
		rArmOriginal.Name = "R_arm_Original"
		rArmOriginal.Value = CFrame.new(Vector3.new(-0.2261, -0.0045, -0.3683)) * CFrame.fromEulerAnglesXYZ(math.rad(90.0012), math.rad(-2.4522), math.rad(90.0012))
		rArmOriginal.Parent = initialPoses
		local rArmInitial = Instance.new("CFrameValue")
		rArmInitial.Name = "R_arm_Initial"
		rArmInitial.Value = CFrame.new(Vector3.new(-0.2261, -0.0045, -0.3683)) * CFrame.fromEulerAnglesXYZ(math.rad(90.0012), math.rad(-2.4522), math.rad(90.0012))
		rArmInitial.Parent = initialPoses
		local rElbowComposited = Instance.new("CFrameValue")
		rElbowComposited.Name = "R_elbow_Composited"
		rElbowComposited.Value = CFrame.new(Vector3.new(0.9383, 3.1303, -0.0352)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		rElbowComposited.Parent = initialPoses
		local rElbowOriginal = Instance.new("CFrameValue")
		rElbowOriginal.Name = "R_elbow_Original"
		rElbowOriginal.Value = CFrame.new(Vector3.xAxis * -0.5701)
		rElbowOriginal.Parent = initialPoses
		local rElbowInitial = Instance.new("CFrameValue")
		rElbowInitial.Name = "R_elbow_Initial"
		rElbowInitial.Value = CFrame.new(Vector3.xAxis * -0.5701)
		rElbowInitial.Parent = initialPoses
		local rHandComposited = Instance.new("CFrameValue")
		rHandComposited.Name = "R_hand_Composited"
		rHandComposited.Value = CFrame.new(Vector3.new(1.4539, 3.1303, -0.0352)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		rHandComposited.Parent = initialPoses
		local rHandOriginal = Instance.new("CFrameValue")
		rHandOriginal.Name = "R_hand_Original"
		rHandOriginal.Value = CFrame.new(Vector3.xAxis * -0.5157)
		rHandOriginal.Parent = initialPoses
		local rHandInitial = Instance.new("CFrameValue")
		rHandInitial.Name = "R_hand_Initial"
		rHandInitial.Value = CFrame.new(Vector3.xAxis * -0.5157)
		rHandInitial.Parent = initialPoses
		local rFingerComposited = Instance.new("CFrameValue")
		rFingerComposited.Name = "R_finger_Composited"
		rFingerComposited.Value = CFrame.new(Vector3.new(1.9061, 3.1303, -0.0352)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		rFingerComposited.Parent = initialPoses
		local rFingerOriginal = Instance.new("CFrameValue")
		rFingerOriginal.Name = "R_finger_Original"
		rFingerOriginal.Value = CFrame.new(Vector3.xAxis * -0.4523)
		rFingerOriginal.Parent = initialPoses
		local rFingerInitial = Instance.new("CFrameValue")
		rFingerInitial.Name = "R_finger_Initial"
		rFingerInitial.Value = CFrame.new(Vector3.xAxis * -0.4523)
		rFingerInitial.Parent = initialPoses
		local tail1Composited = Instance.new("CFrameValue")
		tail1Composited.Name = "tail1_Composited"
		tail1Composited.Value = CFrame.new(Vector3.new(0.0018, 1.9582, -0.0049)) * CFrame.fromEulerAnglesXYZ(math.rad(-1.0492), 0, math.rad(90.0021))
		tail1Composited.Parent = initialPoses
		local tail1Original = Instance.new("CFrameValue")
		tail1Original.Name = "tail1_Original"
		tail1Original.Value = CFrame.new(Vector3.new(0.2446, -0.0172, -0.0019)) * CFrame.fromEulerAnglesXYZ(math.rad(-90), math.rad(2.5042), math.rad(-180))
		tail1Original.Parent = initialPoses
		local tail1Initial = Instance.new("CFrameValue")
		tail1Initial.Name = "tail1_Initial"
		tail1Initial.Value = CFrame.new(Vector3.new(0.2446, -0.0172, -0.0019)) * CFrame.fromEulerAnglesXYZ(math.rad(-90), math.rad(2.5042), math.rad(-180))
		tail1Initial.Parent = initialPoses
		local tail2Composited = Instance.new("CFrameValue")
		tail2Composited.Name = "tail2_Composited"
		tail2Composited.Value = CFrame.new(Vector3.new(0.0018, 1.2807, 0.0075)) * CFrame.fromEulerAnglesXYZ(math.rad(0.2937), 0, math.rad(90))
		tail2Composited.Parent = initialPoses
		local tail2Original = Instance.new("CFrameValue")
		tail2Original.Name = "tail2_Original"
		tail2Original.Value = CFrame.new(Vector3.xAxis * -0.6777) * CFrame.fromEulerAnglesXYZ(0, math.rad(-1.3404), 0)
		tail2Original.Parent = initialPoses
		local tail2Initial = Instance.new("CFrameValue")
		tail2Initial.Name = "tail2_Initial"
		tail2Initial.Value = CFrame.new(Vector3.xAxis * -0.6777) * CFrame.fromEulerAnglesXYZ(0, math.rad(-1.3404), 0)
		tail2Initial.Parent = initialPoses
		local tail3Composited = Instance.new("CFrameValue")
		tail3Composited.Name = "tail3_Composited"
		tail3Composited.Value = CFrame.new(Vector3.new(0.0018, 0.6092, 0.0041)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(90))
		tail3Composited.Parent = initialPoses
		local tail3Original = Instance.new("CFrameValue")
		tail3Original.Name = "tail3_Original"
		tail3Original.Value = CFrame.new(Vector3.new(-0.6716, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, math.rad(0.2918), 0)
		tail3Original.Parent = initialPoses
		local tail3Initial = Instance.new("CFrameValue")
		tail3Initial.Name = "tail3_Initial"
		tail3Initial.Value = CFrame.new(Vector3.new(-0.6716, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, math.rad(0.2918), 0)
		tail3Initial.Parent = initialPoses
		local tail4Composited = Instance.new("CFrameValue")
		tail4Composited.Name = "tail4_Composited"
		tail4Composited.Value = CFrame.new(Vector3.new(0.0018, 0.0266, 0.0041)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(90))
		tail4Composited.Parent = initialPoses
		local tail4Original = Instance.new("CFrameValue")
		tail4Original.Name = "tail4_Original"
		tail4Original.Value = CFrame.new(Vector3.xAxis * -0.5826)
		tail4Original.Parent = initialPoses
		local tail4Initial = Instance.new("CFrameValue")
		tail4Initial.Name = "tail4_Initial"
		tail4Initial.Value = CFrame.new(Vector3.xAxis * -0.5826)
		tail4Initial.Parent = initialPoses
		local connieComposited = Instance.new("CFrameValue")
		connieComposited.Name = "Connie_Composited"
		connieComposited.Value = CFrame.new(Vector3.new(0, 0, -0.2698))
		connieComposited.Parent = initialPoses
		local connieOriginal = Instance.new("CFrameValue")
		connieOriginal.Name = "Connie_Original"
		connieOriginal.Value = CFrame.new(Vector3.new(0, 0, 0.2697)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		connieOriginal.Parent = initialPoses
		local connieInitial = Instance.new("CFrameValue")
		connieInitial.Name = "Connie_Initial"
		connieInitial.Value = CFrame.new(Vector3.new(0, 0, 0.2697)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		connieInitial.Parent = initialPoses
		local upperTorsoComposited = Instance.new("CFrameValue")
		upperTorsoComposited.Name = "UpperTorso_Composited"
		upperTorsoComposited.Value = CFrame.new(Vector3.new(0, 0, -0.2698))
		upperTorsoComposited.Parent = initialPoses
		local upperTorsoOriginal = Instance.new("CFrameValue")
		upperTorsoOriginal.Name = "UpperTorso_Original"
		upperTorsoOriginal.Parent = initialPoses
		local upperTorsoInitial = Instance.new("CFrameValue")
		upperTorsoInitial.Name = "UpperTorso_Initial"
		upperTorsoInitial.Parent = initialPoses
		local rightHandComposited = Instance.new("CFrameValue")
		rightHandComposited.Name = "RightHand_Composited"
		rightHandComposited.Value = CFrame.new(Vector3.new(0, 0, -0.2698))
		rightHandComposited.Parent = initialPoses
		local rightHandOriginal = Instance.new("CFrameValue")
		rightHandOriginal.Name = "RightHand_Original"
		rightHandOriginal.Parent = initialPoses
		local rightHandInitial = Instance.new("CFrameValue")
		rightHandInitial.Name = "RightHand_Initial"
		rightHandInitial.Parent = initialPoses
		local rightUpperrArmComposited = Instance.new("CFrameValue")
		rightUpperrArmComposited.Name = "RightUpperrArm_Composited"
		rightUpperrArmComposited.Value = CFrame.new(Vector3.new(0, 0, -0.2698))
		rightUpperrArmComposited.Parent = initialPoses
		local rightUpperrArmOriginal = Instance.new("CFrameValue")
		rightUpperrArmOriginal.Name = "RightUpperrArm_Original"
		rightUpperrArmOriginal.Parent = initialPoses
		local rightUpperrArmInitial = Instance.new("CFrameValue")
		rightUpperrArmInitial.Name = "RightUpperrArm_Initial"
		rightUpperrArmInitial.Parent = initialPoses
		local leftHandComposited = Instance.new("CFrameValue")
		leftHandComposited.Name = "LeftHand_Composited"
		leftHandComposited.Value = CFrame.new(Vector3.new(0, 0, -0.2698))
		leftHandComposited.Parent = initialPoses
		local leftHandOriginal = Instance.new("CFrameValue")
		leftHandOriginal.Name = "LeftHand_Original"
		leftHandOriginal.Parent = initialPoses
		local leftHandInitial = Instance.new("CFrameValue")
		leftHandInitial.Name = "LeftHand_Initial"
		leftHandInitial.Parent = initialPoses
		local leftUpperArmComposited = Instance.new("CFrameValue")
		leftUpperArmComposited.Name = "LeftUpperArm_Composited"
		leftUpperArmComposited.Value = CFrame.new(Vector3.new(0, 0, -0.2698))
		leftUpperArmComposited.Parent = initialPoses
		local leftUpperArmOriginal = Instance.new("CFrameValue")
		leftUpperArmOriginal.Name = "LeftUpperArm_Original"
		leftUpperArmOriginal.Parent = initialPoses
		local leftUpperArmInitial = Instance.new("CFrameValue")
		leftUpperArmInitial.Name = "LeftUpperArm_Initial"
		leftUpperArmInitial.Parent = initialPoses
		local rightLowerArmComposited = Instance.new("CFrameValue")
		rightLowerArmComposited.Name = "RightLowerArm_Composited"
		rightLowerArmComposited.Value = CFrame.new(Vector3.new(0, 0, -0.2698))
		rightLowerArmComposited.Parent = initialPoses
		local rightLowerArmOriginal = Instance.new("CFrameValue")
		rightLowerArmOriginal.Name = "RightLowerArm_Original"
		rightLowerArmOriginal.Parent = initialPoses
		local rightLowerArmInitial = Instance.new("CFrameValue")
		rightLowerArmInitial.Name = "RightLowerArm_Initial"
		rightLowerArmInitial.Parent = initialPoses
		local leftLowerArmComposited = Instance.new("CFrameValue")
		leftLowerArmComposited.Name = "LeftLowerArm_Composited"
		leftLowerArmComposited.Value = CFrame.new(Vector3.new(0, 0, -0.2698))
		leftLowerArmComposited.Parent = initialPoses
		local leftLowerArmOriginal = Instance.new("CFrameValue")
		leftLowerArmOriginal.Name = "LeftLowerArm_Original"
		leftLowerArmOriginal.Parent = initialPoses
		local leftLowerArmInitial = Instance.new("CFrameValue")
		leftLowerArmInitial.Name = "LeftLowerArm_Initial"
		leftLowerArmInitial.Parent = initialPoses
		local headComposited_2 = Instance.new("CFrameValue")
		headComposited_2.Name = "Head_Composited"
		headComposited_2.Value = CFrame.new(Vector3.new(0, 0, -0.2698))
		headComposited_2.Parent = initialPoses
		local headOriginal_2 = Instance.new("CFrameValue")
		headOriginal_2.Name = "Head_Original"
		headOriginal_2.Parent = initialPoses
		local headInitial_2 = Instance.new("CFrameValue")
		headInitial_2.Name = "Head_Initial"
		headInitial_2.Parent = initialPoses
	end
	initialPoses.Parent = ghastlyGlow
	local animations = Instance.new("Configuration")
	animations.Name = "Animations"
	do
		local walk = Instance.new("Animation")
		walk.Name = "Walk"
		walk.AnimationId = "rbxassetid://118084799741191"
		walk.Parent = animations
		local idle = Instance.new("Animation")
		idle.Name = "Idle"
		idle.AnimationId = "rbxassetid://94596385917656"
		idle.Parent = animations
		local decode = Instance.new("Animation")
		decode.Name = "Decode"
		decode.AnimationId = "rbxassetid://139609244623787"
		decode.Parent = animations
		local run = Instance.new("Animation")
		run.Name = "Run"
		run.AnimationId = "rbxassetid://71674816014662"
		run.Parent = animations
		local quirk = Instance.new("Animation")
		quirk.Name = "Quirk"
		quirk.AnimationId = "rbxassetid://73147494018528"
		quirk.Parent = animations
	end
	animations.Parent = ghastlyGlow
	rootPart = Instance.new("Part")
	rootPart.Name = "RootPart"
	rootPart.CollisionGroup = "Player"
	rootPart.Transparency = 1
	rootPart.CanTouch = false
	rootPart.EnableFluidForces = false
	rootPart.CanCollide = false
	rootPart.CanQuery = false
	rootPart.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
	rootPart.Size = Vector3.new(2, 2, 1)
	rootPart.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
	rootPart.CFrame = CFrame.new(Vector3.new(-51.8894, 2.9481, 57.9064)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	do
		local root = Instance.new("Bone")
		root.Name = "root"
		root.SecondaryAxis = Vector3.new(0, 0.0621, 0.998)
		root.Axis = Vector3.new(0, -0.9981, 0.0621)
		root.CFrame = CFrame.new(Vector3.zAxis * -0.0029) * CFrame.fromEulerAnglesXYZ(math.rad(86.439), math.rad(-90), 0)
		do
			local torso = Instance.new("Bone")
			torso.Name = "torso"
			torso.SecondaryAxis = Vector3.new(0.062, 0.998, 0)
			torso.Axis = Vector3.new(0.998, -0.0621, 0)
			torso.CFrame = CFrame.new(Vector3.new(-0.2652, -0.0018, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(-3.5567))
			do
				local chest = Instance.new("Bone")
				chest.Name = "chest"
				chest.SecondaryAxis = Vector3.new(-0.0429, 0.999, 0)
				chest.Axis = Vector3.new(0.999, 0.0428, 0)
				chest.CFrame = CFrame.new(Vector3.new(-0.4367, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(2.4533))
				do
					local head = Instance.new("Bone")
					head.Name = "head"
					head.CFrame = CFrame.new(Vector3.new(-0.453, -0.019, 0))
					do
						local hair1 = Instance.new("Bone")
						hair1.Name = "hair1"
						hair1.SecondaryAxis = Vector3.new(0, 0, 1)
						hair1.Axis = Vector3.new(-1, -0.0263, 0)
						hair1.CFrame = CFrame.new(Vector3.new(0.3781, 0.8197, 0)) * CFrame.fromEulerAnglesXYZ(math.rad(-89.9959), math.rad(-1.5039), math.rad(-180))
						do
							local hair2 = Instance.new("Bone")
							hair2.Name = "hair2"
							hair2.Axis = Vector3.new(0.803, 0, -0.5959)
							hair2.CFrame = CFrame.new(Vector3.new(-1.015, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, math.rad(36.5744), 0)
							do
								local hair3 = Instance.new("Bone")
								hair3.Name = "hair3"
								hair3.Axis = Vector3.new(0.4656, 0, -0.885)
								hair3.CFrame = CFrame.new(Vector3.new(-0.7072, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, math.rad(62.2485), 0)
								do
									local hair4 = Instance.new("Bone")
									hair4.Name = "hair4"
									hair4.CFrame = CFrame.new(Vector3.new(-0.7748, 0, 0))
									hair4.Parent = hair3
								end
								hair3.Parent = hair2
							end
							hair2.Parent = hair1
						end
						hair1.Parent = head
						attachment = Instance.new("Attachment")
						attachment.CFrame = CFrame.new(Vector3.new(-0.9126, -0.1695, 0))
						attachment.Parent = head
					end
					head.Parent = chest
					local lArm = Instance.new("Bone")
					lArm.Name = "L_arm"
					lArm.SecondaryAxis = Vector3.new(-0.9991, 0.0427, 0)
					lArm.Axis = Vector3.new(0, 0, -1)
					lArm.CFrame = CFrame.new(Vector3.new(-0.2261, -0.0045, 0.3688)) * CFrame.fromEulerAnglesXYZ(math.rad(-90.0013), math.rad(2.4521), math.rad(90.0012))
					do
						local lElbow = Instance.new("Bone")
						lElbow.Name = "L_elbow"
						lElbow.CFrame = CFrame.new(Vector3.new(-0.5703, 0, 0))
						do
							local lHand = Instance.new("Bone")
							lHand.Name = "L_hand"
							lHand.CFrame = CFrame.new(Vector3.xAxis * -0.51)
							do
								local lFinger = Instance.new("Bone")
								lFinger.Name = "L_finger"
								lFinger.CFrame = CFrame.new(Vector3.xAxis * -0.4523)
								lFinger.Parent = lHand
							end
							lHand.Parent = lElbow
						end
						lElbow.Parent = lArm
					end
					lArm.Parent = chest
					local rArm = Instance.new("Bone")
					rArm.Name = "R_arm"
					rArm.SecondaryAxis = Vector3.new(-0.9991, 0.0427, 0)
					rArm.Axis = Vector3.new(0, 0, 1)
					rArm.CFrame = CFrame.new(Vector3.new(-0.2261, -0.0045, -0.3683)) * CFrame.fromEulerAnglesXYZ(math.rad(90.0012), math.rad(-2.4522), math.rad(90.0012))
					do
						local rElbow = Instance.new("Bone")
						rElbow.Name = "R_elbow"
						rElbow.CFrame = CFrame.new(Vector3.new(-0.5701, 0, 0))
						do
							local rHand = Instance.new("Bone")
							rHand.Name = "R_hand"
							rHand.CFrame = CFrame.new(Vector3.xAxis * -0.5157)
							do
								local rFinger = Instance.new("Bone")
								rFinger.Name = "R_finger"
								rFinger.CFrame = CFrame.new(Vector3.xAxis * -0.4523)
								rFinger.Parent = rHand
							end
							rHand.Parent = rElbow
						end
						rElbow.Parent = rArm
					end
					rArm.Parent = chest
				end
				chest.Parent = torso
			end
			torso.Parent = root
			local tail1 = Instance.new("Bone")
			tail1.Name = "tail1"
			tail1.SecondaryAxis = Vector3.new(0, 0, 1)
			tail1.Axis = Vector3.new(-0.9991, 0.0436, 0)
			tail1.CFrame = CFrame.new(Vector3.new(0.2446, -0.0172, -0.0019)) * CFrame.fromEulerAnglesXYZ(math.rad(-90), math.rad(2.5042), math.rad(-180))
			do
				local tail2 = Instance.new("Bone")
				tail2.Name = "tail2"
				tail2.Axis = Vector3.new(1, 0, 0.0233)
				tail2.CFrame = CFrame.new(Vector3.new(-0.6777, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-1.3404), 0)
				do
					local tail3 = Instance.new("Bone")
					tail3.Name = "tail3"
					tail3.Axis = Vector3.new(1, 0, -0.0051)
					tail3.CFrame = CFrame.new(Vector3.new(-0.6716, 0, 0)) * CFrame.fromEulerAnglesXYZ(0, math.rad(0.2918), 0)
					do
						local tail4 = Instance.new("Bone")
						tail4.Name = "tail4"
						tail4.CFrame = CFrame.new(Vector3.xAxis * -0.5826)
						tail4.Parent = tail3
					end
					tail3.Parent = tail2
				end
				tail2.Parent = tail1
			end
			tail1.Parent = root
		end
		root.Parent = rootPart
		weld = Instance.new("Weld")
		weld.Parent = rootPart
		joint = Instance.new("Motor6D")
		joint.Name = "Joint"
		joint.Parent = rootPart
	end
	rootPart.Parent = ghastlyGlow
	head_2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://77078637919579", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	head_2.TextureID = "rbxassetid://130099326342245"
	head_2.Name = "Head"
	head_2.CollisionGroup = "Player"
	head_2.Transparency = 1
	head_2.CanCollide = false
	head_2.CanQuery = false
	head_2.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
	head_2.Size = Vector3.new(2.8121, 4.9954, 3.8351)
	head_2.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
	head_2.Color = Color3.fromRGB(178, 252, 255)
	head_2.CFrame = CFrame.new(Vector3.new(-52.6226, 4.3727, 57.9265)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	head_2.PivotOffset = CFrame.identity
	do
		headMotor6d = Instance.new("Motor6D")
		headMotor6d.Name = "HeadMotor6D"
		headMotor6d.MaxVelocity = 0.1
		headMotor6d.C0 = CFrame.new(Vector3.new(0.02, 3.6241, 0.7332))
		headMotor6d.C1 = CFrame.new(Vector3.yAxis * 2.1996)
		headMotor6d.Parent = head_2
		nameTagOverride = Instance.new("ObjectValue")
		nameTagOverride.Name = "NameTagOverride"
		nameTagOverride.Parent = head_2
		head_3 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://77078637919579", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		head_3.TextureID = "rbxassetid://130099326342245"
		head_3.Name = "Head"
		head_3.Transparency = 1
		head_3.CanQuery = false
		head_3.EnableFluidForces = false
		head_3.CanTouch = false
		head_3.CanCollide = false
		head_3.Size = Vector3.new(2.8121, 4.9954, 3.8351)
		head_3.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
		head_3.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
		head_3.Color = Color3.fromRGB(178, 252, 255)
		head_3.CFrame = CFrame.new(Vector3.new(-52.6226, 4.3727, 57.9265)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
		head_3.PivotOffset = CFrame.identity
		do
			headMotor6d_2 = Instance.new("Motor6D")
			headMotor6d_2.Name = "HeadMotor6D"
			headMotor6d_2.MaxVelocity = 0.1
			headMotor6d_2.C0 = CFrame.new(Vector3.new(0.02, 3.6241, 0.7332))
			headMotor6d_2.Parent = head_3
			local bubbleChat = Instance.new("Attachment")
			bubbleChat.Name = "BubbleChat"
			bubbleChat.CFrame = CFrame.new(Vector3.new(0, 1, -1.4798))
			bubbleChat.Parent = head_3
			local stickerOverride = Instance.new("Attachment")
			stickerOverride.Name = "StickerOverride"
			stickerOverride.CFrame = CFrame.new(Vector3.yAxis * 2.0429)
			stickerOverride.Parent = head_3
			weld_2 = Instance.new("Weld")
			weld_2.Parent = head_3
			head_4 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://98037867491596", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
			head_4.TextureID = "rbxassetid://130099326342245"
			head_4.Name = "Head"
			head_4.CanCollide = false
			head_4.CanTouch = false
			head_4.Massless = true
			head_4.CanQuery = false
			head_4.Size = Vector3.new(2.9578, 5.6146, 3.7258)
			head_4.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
			head_4.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
			head_4.CFrame = CFrame.new(Vector3.new(-52.6226, 4.3727, 57.9265)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
			head_4.PivotOffset = CFrame.new(Vector3.new(0, -0.3097, -0.0547))
			do
				headMotor6d_3 = Instance.new("Motor6D")
				headMotor6d_3.Name = "HeadMotor6D"
				headMotor6d_3.MaxVelocity = 0.1
				headMotor6d_3.C0 = CFrame.new(Vector3.new(0.0216, 3.9341, 0.7913))
				headMotor6d_3.Parent = head_4
				weld_3 = Instance.new("Weld")
				weld_3.Parent = head_4
			end
			head_4.Parent = head_3
		end
		head_3.Parent = head_2
	end
	head_2.Parent = ghastlyGlow
	humanoidRootPart = Instance.new("Part")
	humanoidRootPart.Name = "HumanoidRootPart"
	humanoidRootPart.CollisionGroup = "Player"
	humanoidRootPart.Transparency = 1
	humanoidRootPart.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
	humanoidRootPart.Size = Vector3.new(2, 2, 1)
	humanoidRootPart.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
	humanoidRootPart.CFrame = CFrame.new(Vector3.new(-51.8894, 2.9481, 57.9064)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	do
		local particleThing = Instance.new("ParticleEmitter")
		particleThing.Name = "ParticleThing"
		particleThing.Texture = "rbxassetid://18850392282"
		particleThing.Rate = 0.75
		particleThing.LightInfluence = 0.5
		particleThing.Enabled = false
		particleThing.Acceleration = Vector3.yAxis * 0.1
		particleThing.SpreadAngle = Vector2.one * 100
		particleThing.Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 1), NumberSequenceKeypoint.new(0.0846, 0.3499), NumberSequenceKeypoint.new(0.1357, 0.3437), NumberSequenceKeypoint.new(0.716, 0.3874), NumberSequenceKeypoint.new(1, 1)})
		particleThing.Size = NumberSequence.new({NumberSequenceKeypoint.new(0, 0), NumberSequenceKeypoint.new(0.4956, 0.2499, 0.125), NumberSequenceKeypoint.new(1, 0)})
		particleThing.Lifetime = NumberRange.new(5)
		particleThing.Color = ColorSequence.new(Color3.fromRGB(184, 167, 127), Color3.fromRGB(184, 167, 127))
		particleThing.Parent = humanoidRootPart
		local extraLight = Instance.new("Attachment")
		extraLight.Name = "ExtraLight"
		extraLight.CFrame = CFrame.new(Vector3.new(0, 1.5873, -1.8427))
		do
			local pointLight = Instance.new("PointLight")
			pointLight.Range = 4
			pointLight.Enabled = false
			pointLight.Color = Color3.fromRGB(198, 198, 222)
			pointLight.Parent = extraLight
		end
		extraLight.Parent = humanoidRootPart
		local toonLight = Instance.new("Attachment")
		toonLight.Name = "ToonLight"
		toonLight.CFrame = CFrame.new(Vector3.new(0, 1.6486, 0.0337))
		do
			local pointLight_2 = Instance.new("PointLight")
			pointLight_2.Brightness = 1.5
			pointLight_2.Range = 33
			pointLight_2.Enabled = false
			pointLight_2.Color = Color3.fromRGB(198, 198, 222)
			pointLight_2.Parent = toonLight
		end
		toonLight.Parent = humanoidRootPart
	end
	humanoidRootPart.Parent = ghastlyGlow
	leftLowerArm = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://104676464803486", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	leftLowerArm.TextureID = "rbxassetid://130099326342245"
	leftLowerArm.Name = "LeftLowerArm"
	leftLowerArm.CollisionGroup = "Player"
	leftLowerArm.Transparency = 1
	leftLowerArm.CanCollide = false
	leftLowerArm.CanQuery = false
	leftLowerArm.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
	leftLowerArm.Size = Vector3.new(0.6938, 0.296, 0.3159)
	leftLowerArm.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
	leftLowerArm.Color = Color3.fromRGB(178, 252, 255)
	leftLowerArm.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 56.7069)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	leftLowerArm.PivotOffset = CFrame.new(Vector3.new(0.0055, 0, 0))
	do
		leftLowerArmMotor6d = Instance.new("Motor6D")
		leftLowerArmMotor6d.Name = "LeftLowerArmMotor6D"
		leftLowerArmMotor6d.MaxVelocity = 0.1
		leftLowerArmMotor6d.C0 = CFrame.new(Vector3.new(-1.1995, 3.1313, -0.0357))
		leftLowerArmMotor6d.C1 = CFrame.new(Vector3.yAxis * 2.1996)
		leftLowerArmMotor6d.Parent = leftLowerArm
		leftLowerArm_2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://104676464803486", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		leftLowerArm_2.TextureID = "rbxassetid://130099326342245"
		leftLowerArm_2.Name = "LeftLowerArm"
		leftLowerArm_2.Transparency = 1
		leftLowerArm_2.CanCollide = false
		leftLowerArm_2.CanQuery = false
		leftLowerArm_2.CanTouch = false
		leftLowerArm_2.EnableFluidForces = false
		leftLowerArm_2.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
		leftLowerArm_2.Size = Vector3.new(0.6938, 0.296, 0.3159)
		leftLowerArm_2.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
		leftLowerArm_2.Material = Enum.Material.SmoothPlastic
		leftLowerArm_2.Color = Color3.fromRGB(178, 252, 255)
		leftLowerArm_2.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 56.7069)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
		leftLowerArm_2.PivotOffset = CFrame.new(Vector3.new(0.0055, 0, 0))
		do
			leftLowerArmMotor6d_2 = Instance.new("Motor6D")
			leftLowerArmMotor6d_2.Name = "LeftLowerArmMotor6D"
			leftLowerArmMotor6d_2.MaxVelocity = 0.1
			leftLowerArmMotor6d_2.C0 = CFrame.new(Vector3.new(-1.1995, 3.1313, -0.0357))
			leftLowerArmMotor6d_2.Parent = leftLowerArm_2
			weld_4 = Instance.new("Weld")
			weld_4.Parent = leftLowerArm_2
			leftLowerArm_3 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://82586984493745", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
			leftLowerArm_3.TextureID = "rbxassetid://130099326342245"
			leftLowerArm_3.Name = "LeftLowerArm"
			leftLowerArm_3.CanCollide = false
			leftLowerArm_3.CanTouch = false
			leftLowerArm_3.Massless = true
			leftLowerArm_3.CanQuery = false
			leftLowerArm_3.Size = Vector3.new(0.6908, 0.2944, 0.3079)
			leftLowerArm_3.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
			leftLowerArm_3.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
			leftLowerArm_3.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 56.7069)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
			leftLowerArm_3.PivotOffset = CFrame.new(Vector3.new(0.0046, 0, 0))
			do
				leftLowerArmMotor6d_3 = Instance.new("Motor6D")
				leftLowerArmMotor6d_3.Name = "LeftLowerArmMotor6D"
				leftLowerArmMotor6d_3.MaxVelocity = 0.1
				leftLowerArmMotor6d_3.C0 = CFrame.new(Vector3.new(-1.177, 3.1317, -0.0322))
				leftLowerArmMotor6d_3.Parent = leftLowerArm_3
				weld_5 = Instance.new("Weld")
				weld_5.Parent = leftLowerArm_3
			end
			leftLowerArm_3.Parent = leftLowerArm_2
		end
		leftLowerArm_2.Parent = leftLowerArm
	end
	leftLowerArm.Parent = ghastlyGlow
	upperTorso = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://96764574975304", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	upperTorso.TextureID = "rbxassetid://130099326342245"
	upperTorso.Name = "UpperTorso"
	upperTorso.CollisionGroup = "Player"
	upperTorso.Transparency = 1
	upperTorso.CanCollide = false
	upperTorso.CanQuery = false
	upperTorso.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
	upperTorso.Size = Vector3.new(0.8994, 4.1734, 0.7604)
	upperTorso.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
	upperTorso.Color = Color3.fromRGB(178, 252, 255)
	upperTorso.CFrame = CFrame.new(Vector3.new(-51.8504, 2.0688, 57.904)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	upperTorso.PivotOffset = CFrame.new(Vector3.new(0, 0.1715, -0.0128))
	do
		upperTorsoMotor6d = Instance.new("Motor6D")
		upperTorsoMotor6d.Name = "UpperTorsoMotor6D"
		upperTorsoMotor6d.MaxVelocity = 0.1
		upperTorsoMotor6d.C0 = CFrame.new(Vector3.new(-0.0025, 1.3202, -0.0391))
		upperTorsoMotor6d.C1 = CFrame.new(Vector3.yAxis * 2.1996)
		upperTorsoMotor6d.Parent = upperTorso
		upperTorso_2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://96764574975304", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		upperTorso_2.TextureID = "rbxassetid://130099326342245"
		upperTorso_2.Name = "UpperTorso"
		upperTorso_2.Transparency = 1
		upperTorso_2.CanQuery = false
		upperTorso_2.EnableFluidForces = false
		upperTorso_2.CanTouch = false
		upperTorso_2.CanCollide = false
		upperTorso_2.Size = Vector3.new(0.8994, 4.1734, 0.7604)
		upperTorso_2.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
		upperTorso_2.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
		upperTorso_2.Color = Color3.fromRGB(178, 252, 255)
		upperTorso_2.CFrame = CFrame.new(Vector3.new(-51.8504, 2.0688, 57.904)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
		upperTorso_2.PivotOffset = CFrame.new(Vector3.new(0, 0.1715, -0.0128))
		do
			upperTorsoMotor6d_2 = Instance.new("Motor6D")
			upperTorsoMotor6d_2.Name = "UpperTorsoMotor6D"
			upperTorsoMotor6d_2.MaxVelocity = 0.1
			upperTorsoMotor6d_2.C0 = CFrame.new(Vector3.new(-0.0025, 1.3202, -0.0391))
			upperTorsoMotor6d_2.Parent = upperTorso_2
			weld_6 = Instance.new("Weld")
			weld_6.Parent = upperTorso_2
			torso_2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://94238113650294", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
			torso_2.TextureID = "rbxassetid://130099326342245"
			torso_2.Name = "Torso"
			torso_2.Massless = true
			torso_2.CanTouch = false
			torso_2.CanQuery = false
			torso_2.Size = Vector3.new(1.5043, 4.1734, 1.1659)
			torso_2.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
			torso_2.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
			torso_2.CFrame = CFrame.new(Vector3.new(-51.8504, 2.0688, 57.904)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
			torso_2.PivotOffset = CFrame.new(Vector3.new(0.0034, 0, -0.0275))
			do
				torsoMotor6d = Instance.new("Motor6D")
				torsoMotor6d.Name = "TorsoMotor6D"
				torsoMotor6d.MaxVelocity = 0.1
				torsoMotor6d.C0 = CFrame.new(Vector3.new(0.0157, 1.3206, -0.0081))
				torsoMotor6d.Parent = torso_2
				weld_7 = Instance.new("Weld")
				weld_7.Parent = torso_2
			end
			torso_2.Parent = upperTorso_2
		end
		upperTorso_2.Parent = upperTorso
	end
	upperTorso.Parent = ghastlyGlow
	rightHand = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://81014163911064", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	rightHand.TextureID = "rbxassetid://130099326342245"
	rightHand.Name = "RightHand"
	rightHand.CollisionGroup = "Player"
	rightHand.Transparency = 1
	rightHand.CanCollide = false
	rightHand.CanQuery = false
	rightHand.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
	rightHand.Size = Vector3.new(0.7163, 0.6002, 0.2586)
	rightHand.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
	rightHand.Color = Color3.fromRGB(178, 252, 255)
	rightHand.CFrame = CFrame.new(Vector3.new(-51.8537, 3.9474, 59.619)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	rightHand.PivotOffset = CFrame.new(Vector3.new(0, -0.0036, 0))
	do
		rightHandMotor6d = Instance.new("Motor6D")
		rightHandMotor6d.Name = "RightHandMotor6D"
		rightHandMotor6d.MaxVelocity = 0.1
		rightHandMotor6d.C0 = CFrame.new(Vector3.new(1.7126, 3.1989, -0.0357))
		rightHandMotor6d.C1 = CFrame.new(Vector3.yAxis * 2.1996)
		rightHandMotor6d.Parent = rightHand
		rightHand_2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://81014163911064", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		rightHand_2.TextureID = "rbxassetid://130099326342245"
		rightHand_2.Name = "RightHand"
		rightHand_2.Transparency = 1
		rightHand_2.CanCollide = false
		rightHand_2.CanQuery = false
		rightHand_2.CanTouch = false
		rightHand_2.EnableFluidForces = false
		rightHand_2.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
		rightHand_2.Size = Vector3.new(0.7163, 0.6002, 0.2586)
		rightHand_2.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
		rightHand_2.Material = Enum.Material.SmoothPlastic
		rightHand_2.Color = Color3.fromRGB(178, 252, 255)
		rightHand_2.CFrame = CFrame.new(Vector3.new(-51.8537, 3.9474, 59.619)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
		rightHand_2.PivotOffset = CFrame.new(Vector3.new(0, -0.0036, 0))
		do
			rightHandMotor6d_2 = Instance.new("Motor6D")
			rightHandMotor6d_2.Name = "RightHandMotor6D"
			rightHandMotor6d_2.MaxVelocity = 0.1
			rightHandMotor6d_2.C0 = CFrame.new(Vector3.new(1.7126, 3.1989, -0.0357))
			rightHandMotor6d_2.Parent = rightHand_2
			weld_8 = Instance.new("Weld")
			weld_8.Parent = rightHand_2
			rightHand_3 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://123635199963711", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
			rightHand_3.TextureID = "rbxassetid://130099326342245"
			rightHand_3.Name = "RightHand"
			rightHand_3.CanCollide = false
			rightHand_3.CanTouch = false
			rightHand_3.Massless = true
			rightHand_3.CanQuery = false
			rightHand_3.Size = Vector3.new(0.7059, 0.5961, 0.2367)
			rightHand_3.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
			rightHand_3.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
			rightHand_3.CFrame = CFrame.new(Vector3.new(-51.8537, 3.9474, 59.619)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
			rightHand_3.PivotOffset = CFrame.identity
			do
				rightHandMotor6d_3 = Instance.new("Motor6D")
				rightHandMotor6d_3.Name = "RightHandMotor6D"
				rightHandMotor6d_3.MaxVelocity = 0.1
				rightHandMotor6d_3.C0 = CFrame.new(Vector3.new(1.7316, 3.1977, -0.0323))
				rightHandMotor6d_3.Parent = rightHand_3
				weld_9 = Instance.new("Weld")
				weld_9.Parent = rightHand_3
			end
			rightHand_3.Parent = rightHand_2
		end
		rightHand_2.Parent = rightHand
	end
	rightHand.Parent = ghastlyGlow
	rightUpperrArm = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://98919602711214", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	rightUpperrArm.TextureID = "rbxassetid://130099326342245"
	rightUpperrArm.Name = "RightUpperrArm"
	rightUpperrArm.CollisionGroup = "Player"
	rightUpperrArm.Transparency = 1
	rightUpperrArm.CanCollide = false
	rightUpperrArm.CanQuery = false
	rightUpperrArm.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
	rightUpperrArm.Size = Vector3.new(0.7517, 0.2913, 0.3456)
	rightUpperrArm.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
	rightUpperrArm.Color = Color3.fromRGB(178, 252, 255)
	rightUpperrArm.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 58.5567)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	rightUpperrArm.PivotOffset = CFrame.identity
	do
		rightUpperrArmMotor6d = Instance.new("Motor6D")
		rightUpperrArmMotor6d.Name = "RightUpperrArmMotor6D"
		rightUpperrArmMotor6d.MaxVelocity = 0.1
		rightUpperrArmMotor6d.C0 = CFrame.new(Vector3.new(0.6502, 3.1313, -0.0357))
		rightUpperrArmMotor6d.C1 = CFrame.new(Vector3.yAxis * 2.1996)
		rightUpperrArmMotor6d.Parent = rightUpperrArm
		rightUpperrArm_2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://98919602711214", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		rightUpperrArm_2.TextureID = "rbxassetid://130099326342245"
		rightUpperrArm_2.Name = "RightUpperrArm"
		rightUpperrArm_2.Transparency = 1
		rightUpperrArm_2.CanCollide = false
		rightUpperrArm_2.CanQuery = false
		rightUpperrArm_2.CanTouch = false
		rightUpperrArm_2.EnableFluidForces = false
		rightUpperrArm_2.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
		rightUpperrArm_2.Size = Vector3.new(0.7517, 0.2913, 0.3456)
		rightUpperrArm_2.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
		rightUpperrArm_2.Material = Enum.Material.SmoothPlastic
		rightUpperrArm_2.Color = Color3.fromRGB(178, 252, 255)
		rightUpperrArm_2.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 58.5567)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
		rightUpperrArm_2.PivotOffset = CFrame.identity
		do
			rightUpperrArmMotor6d_2 = Instance.new("Motor6D")
			rightUpperrArmMotor6d_2.Name = "RightUpperrArmMotor6D"
			rightUpperrArmMotor6d_2.MaxVelocity = 0.1
			rightUpperrArmMotor6d_2.C0 = CFrame.new(Vector3.new(0.6502, 3.1313, -0.0357))
			rightUpperrArmMotor6d_2.Parent = rightUpperrArm_2
			weld_10 = Instance.new("Weld")
			weld_10.Parent = rightUpperrArm_2
			rightUpperArm = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://73889958325100", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
			rightUpperArm.TextureID = "rbxassetid://130099326342245"
			rightUpperArm.Name = "RightUpperArm"
			rightUpperArm.CanCollide = false
			rightUpperArm.CanTouch = false
			rightUpperArm.Massless = true
			rightUpperArm.CanQuery = false
			rightUpperArm.Size = Vector3.new(0.7413, 0.2956, 0.3795)
			rightUpperArm.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
			rightUpperArm.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
			rightUpperArm.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 58.5567)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
			rightUpperArm.PivotOffset = CFrame.new(Vector3.new(-0.0044, 0, 0))
			do
				rightUpperArmMotor6d = Instance.new("Motor6D")
				rightUpperArmMotor6d.Name = "RightUpperArmMotor6D"
				rightUpperArmMotor6d.MaxVelocity = 0.1
				rightUpperArmMotor6d.C0 = CFrame.new(Vector3.new(0.6761, 3.1316, -0.0322))
				rightUpperArmMotor6d.Parent = rightUpperArm
				weld_11 = Instance.new("Weld")
				weld_11.Parent = rightUpperArm
			end
			rightUpperArm.Parent = rightUpperrArm_2
		end
		rightUpperrArm_2.Parent = rightUpperrArm
	end
	rightUpperrArm.Parent = ghastlyGlow
	leftHand = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://137534967382967", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	leftHand.TextureID = "rbxassetid://130099326342245"
	leftHand.Name = "LeftHand"
	leftHand.CollisionGroup = "Player"
	leftHand.Transparency = 1
	leftHand.CanCollide = false
	leftHand.CanQuery = false
	leftHand.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
	leftHand.Size = Vector3.new(0.7163, 0.6002, 0.2586)
	leftHand.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
	leftHand.Color = Color3.fromRGB(178, 252, 255)
	leftHand.CFrame = CFrame.new(Vector3.new(-51.8537, 3.9474, 56.1938)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	leftHand.PivotOffset = CFrame.new(Vector3.new(0, -0.0036, 0))
	do
		leftHandMotor6d = Instance.new("Motor6D")
		leftHandMotor6d.Name = "LeftHandMotor6D"
		leftHandMotor6d.MaxVelocity = 0.1
		leftHandMotor6d.C0 = CFrame.new(Vector3.new(-1.7127, 3.1989, -0.0357))
		leftHandMotor6d.C1 = CFrame.new(Vector3.yAxis * 2.1996)
		leftHandMotor6d.Parent = leftHand
		leftHand_2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://137534967382967", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		leftHand_2.TextureID = "rbxassetid://130099326342245"
		leftHand_2.Name = "LeftHand"
		leftHand_2.Transparency = 1
		leftHand_2.CanCollide = false
		leftHand_2.CanQuery = false
		leftHand_2.CanTouch = false
		leftHand_2.EnableFluidForces = false
		leftHand_2.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
		leftHand_2.Size = Vector3.new(0.7163, 0.6002, 0.2586)
		leftHand_2.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
		leftHand_2.Material = Enum.Material.SmoothPlastic
		leftHand_2.Color = Color3.fromRGB(178, 252, 255)
		leftHand_2.CFrame = CFrame.new(Vector3.new(-51.8537, 3.9474, 56.1938)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
		leftHand_2.PivotOffset = CFrame.new(Vector3.new(0, -0.0036, 0))
		do
			leftHandMotor6d_2 = Instance.new("Motor6D")
			leftHandMotor6d_2.Name = "LeftHandMotor6D"
			leftHandMotor6d_2.MaxVelocity = 0.1
			leftHandMotor6d_2.C0 = CFrame.new(Vector3.new(-1.7127, 3.1989, -0.0357))
			leftHandMotor6d_2.Parent = leftHand_2
			weld_12 = Instance.new("Weld")
			weld_12.Parent = leftHand_2
			leftHand_3 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://121520486807728", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
			leftHand_3.TextureID = "rbxassetid://130099326342245"
			leftHand_3.Name = "LeftHand"
			leftHand_3.CanCollide = false
			leftHand_3.CanTouch = false
			leftHand_3.Massless = true
			leftHand_3.CanQuery = false
			leftHand_3.Size = Vector3.new(0.7059, 0.5961, 0.2367)
			leftHand_3.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
			leftHand_3.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
			leftHand_3.CFrame = CFrame.new(Vector3.new(-51.8537, 3.9474, 56.1938)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
			leftHand_3.PivotOffset = CFrame.identity
			do
				leftHandMotor6d_3 = Instance.new("Motor6D")
				leftHandMotor6d_3.Name = "LeftHandMotor6D"
				leftHandMotor6d_3.MaxVelocity = 0.1
				leftHandMotor6d_3.C0 = CFrame.new(Vector3.new(-1.6884, 3.1977, -0.0323))
				leftHandMotor6d_3.Parent = leftHand_3
				weld_13 = Instance.new("Weld")
				weld_13.Parent = leftHand_3
			end
			leftHand_3.Parent = leftHand_2
		end
		leftHand_2.Parent = leftHand
	end
	leftHand.Parent = ghastlyGlow
	leftUpperArm = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://89119732426979", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	leftUpperArm.TextureID = "rbxassetid://130099326342245"
	leftUpperArm.Name = "LeftUpperArm"
	leftUpperArm.CollisionGroup = "Player"
	leftUpperArm.Transparency = 1
	leftUpperArm.CanCollide = false
	leftUpperArm.CanQuery = false
	leftUpperArm.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
	leftUpperArm.Size = Vector3.new(0.7514, 0.2913, 0.3456)
	leftUpperArm.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
	leftUpperArm.Color = Color3.fromRGB(178, 252, 255)
	leftUpperArm.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 57.2563)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	leftUpperArm.PivotOffset = CFrame.identity
	do
		leftUpperArmMotor6d = Instance.new("Motor6D")
		leftUpperArmMotor6d.Name = "LeftUpperArmMotor6D"
		leftUpperArmMotor6d.MaxVelocity = 0.1
		leftUpperArmMotor6d.C0 = CFrame.new(Vector3.new(-0.6502, 3.1313, -0.0357))
		leftUpperArmMotor6d.C1 = CFrame.new(Vector3.yAxis * 2.1996)
		leftUpperArmMotor6d.Parent = leftUpperArm
		leftUpperArm_2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://89119732426979", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		leftUpperArm_2.TextureID = "rbxassetid://130099326342245"
		leftUpperArm_2.Name = "LeftUpperArm"
		leftUpperArm_2.Transparency = 1
		leftUpperArm_2.CanCollide = false
		leftUpperArm_2.CanQuery = false
		leftUpperArm_2.CanTouch = false
		leftUpperArm_2.EnableFluidForces = false
		leftUpperArm_2.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
		leftUpperArm_2.Size = Vector3.new(0.7514, 0.2913, 0.3456)
		leftUpperArm_2.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
		leftUpperArm_2.Material = Enum.Material.SmoothPlastic
		leftUpperArm_2.Color = Color3.fromRGB(178, 252, 255)
		leftUpperArm_2.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 57.2563)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
		leftUpperArm_2.PivotOffset = CFrame.identity
		do
			leftUpperArmMotor6d_2 = Instance.new("Motor6D")
			leftUpperArmMotor6d_2.Name = "LeftUpperArmMotor6D"
			leftUpperArmMotor6d_2.MaxVelocity = 0.1
			leftUpperArmMotor6d_2.C0 = CFrame.new(Vector3.new(-0.6502, 3.1313, -0.0357))
			leftUpperArmMotor6d_2.Parent = leftUpperArm_2
			weld_14 = Instance.new("Weld")
			weld_14.Parent = leftUpperArm_2
			leftUpperArm_3 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://105060661123722", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
			leftUpperArm_3.TextureID = "rbxassetid://130099326342245"
			leftUpperArm_3.Name = "LeftUpperArm"
			leftUpperArm_3.CanCollide = false
			leftUpperArm_3.CanTouch = false
			leftUpperArm_3.Massless = true
			leftUpperArm_3.CanQuery = false
			leftUpperArm_3.Size = Vector3.new(0.7413, 0.2956, 0.3795)
			leftUpperArm_3.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
			leftUpperArm_3.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
			leftUpperArm_3.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 57.2563)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
			leftUpperArm_3.PivotOffset = CFrame.new(Vector3.new(0.0043, 0, 0))
			do
				leftUpperArmMotor6d_3 = Instance.new("Motor6D")
				leftUpperArmMotor6d_3.Name = "LeftUpperArmMotor6D"
				leftUpperArmMotor6d_3.MaxVelocity = 0.1
				leftUpperArmMotor6d_3.C0 = CFrame.new(Vector3.new(-0.6329, 3.1316, -0.0322))
				leftUpperArmMotor6d_3.Parent = leftUpperArm_3
				weld_15 = Instance.new("Weld")
				weld_15.Parent = leftUpperArm_3
			end
			leftUpperArm_3.Parent = leftUpperArm_2
		end
		leftUpperArm_2.Parent = leftUpperArm
	end
	leftUpperArm.Parent = ghastlyGlow
	rightLowerArm = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://125189555119269", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	rightLowerArm.TextureID = "rbxassetid://130099326342245"
	rightLowerArm.Name = "RightLowerArm"
	rightLowerArm.CollisionGroup = "Player"
	rightLowerArm.Transparency = 1
	rightLowerArm.CanCollide = false
	rightLowerArm.CanQuery = false
	rightLowerArm.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
	rightLowerArm.Size = Vector3.new(0.6936, 0.296, 0.3159)
	rightLowerArm.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
	rightLowerArm.Color = Color3.fromRGB(178, 252, 255)
	rightLowerArm.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 59.1057)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
	rightLowerArm.PivotOffset = CFrame.new(Vector3.new(-0.0055, 0, 0))
	do
		rightLowerArmMotor6d = Instance.new("Motor6D")
		rightLowerArmMotor6d.Name = "RightLowerArmMotor6D"
		rightLowerArmMotor6d.MaxVelocity = 0.1
		rightLowerArmMotor6d.C0 = CFrame.new(Vector3.new(1.1993, 3.1313, -0.0357))
		rightLowerArmMotor6d.C1 = CFrame.new(Vector3.yAxis * 2.1996)
		rightLowerArmMotor6d.Parent = rightLowerArm
		rightLowerArm_2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://125189555119269", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		rightLowerArm_2.TextureID = "rbxassetid://130099326342245"
		rightLowerArm_2.Name = "RightLowerArm"
		rightLowerArm_2.Transparency = 1
		rightLowerArm_2.CanCollide = false
		rightLowerArm_2.CanQuery = false
		rightLowerArm_2.CanTouch = false
		rightLowerArm_2.EnableFluidForces = false
		rightLowerArm_2.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
		rightLowerArm_2.Size = Vector3.new(0.6936, 0.296, 0.3159)
		rightLowerArm_2.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
		rightLowerArm_2.Material = Enum.Material.SmoothPlastic
		rightLowerArm_2.Color = Color3.fromRGB(178, 252, 255)
		rightLowerArm_2.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 59.1057)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
		rightLowerArm_2.PivotOffset = CFrame.new(Vector3.new(-0.0055, 0, 0))
		do
			rightLowerArmMotor6d_2 = Instance.new("Motor6D")
			rightLowerArmMotor6d_2.Name = "RightLowerArmMotor6D"
			rightLowerArmMotor6d_2.MaxVelocity = 0.1
			rightLowerArmMotor6d_2.C0 = CFrame.new(Vector3.new(1.1993, 3.1313, -0.0357))
			rightLowerArmMotor6d_2.Parent = rightLowerArm_2
			weld_16 = Instance.new("Weld")
			weld_16.Parent = rightLowerArm_2
			rightLowerArm_3 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://116879466767306", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
			rightLowerArm_3.TextureID = "rbxassetid://130099326342245"
			rightLowerArm_3.Name = "RightLowerArm"
			rightLowerArm_3.CanCollide = false
			rightLowerArm_3.CanTouch = false
			rightLowerArm_3.Massless = true
			rightLowerArm_3.CanQuery = false
			rightLowerArm_3.Size = Vector3.new(0.6908, 0.2944, 0.3079)
			rightLowerArm_3.AssemblyAngularVelocity = Vector3.new(0, 0, 0)
			rightLowerArm_3.AssemblyLinearVelocity = Vector3.new(0, 0, 0)
			rightLowerArm_3.CFrame = CFrame.new(Vector3.new(-51.8537, 3.8799, 59.1057)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-90), 0)
			rightLowerArm_3.PivotOffset = CFrame.new(Vector3.new(-0.0047, 0, 0))
			do
				rightLowerArmMotor6d_3 = Instance.new("Motor6D")
				rightLowerArmMotor6d_3.Name = "RightLowerArmMotor6D"
				rightLowerArmMotor6d_3.MaxVelocity = 0.1
				rightLowerArmMotor6d_3.C0 = CFrame.new(Vector3.new(1.2202, 3.1317, -0.0322))
				rightLowerArmMotor6d_3.Parent = rightLowerArm_3
				weld_17 = Instance.new("Weld")
				weld_17.Parent = rightLowerArm_3
			end
			rightLowerArm_3.Parent = rightLowerArm_2
		end
		rightLowerArm_2.Parent = rightLowerArm
	end
	rightLowerArm.Parent = ghastlyGlow
end

ghastlyGlow.PrimaryPart = rootPart
weld.Part1 = humanoidRootPart
weld.Part0 = rootPart
joint.Part1 = rootPart
joint.Part0 = humanoidRootPart
headMotor6d.Part0 = rootPart
headMotor6d.Part1 = head_2
nameTagOverride.Value = attachment
headMotor6d_2.Part1 = head_3
weld_2.Part1 = head_2
weld_2.Part0 = head_3
headMotor6d_3.Part1 = head_4
weld_3.Part1 = head_3
weld_3.Part0 = head_4
leftLowerArmMotor6d.Part0 = rootPart
leftLowerArmMotor6d.Part1 = leftLowerArm
leftLowerArmMotor6d_2.Part1 = leftLowerArm_2
weld_4.Part1 = leftLowerArm
weld_4.Part0 = leftLowerArm_2
leftLowerArmMotor6d_3.Part1 = leftLowerArm_3
weld_5.Part1 = leftLowerArm_2
weld_5.Part0 = leftLowerArm_3
upperTorsoMotor6d.Part0 = rootPart
upperTorsoMotor6d.Part1 = upperTorso
upperTorsoMotor6d_2.Part1 = upperTorso_2
weld_6.Part1 = upperTorso
weld_6.Part0 = upperTorso_2
torsoMotor6d.Part1 = torso_2
weld_7.Part1 = upperTorso_2
weld_7.Part0 = torso_2
rightHandMotor6d.Part0 = rootPart
rightHandMotor6d.Part1 = rightHand
rightHandMotor6d_2.Part1 = rightHand_2
weld_8.Part1 = rightHand
weld_8.Part0 = rightHand_2
rightHandMotor6d_3.Part1 = rightHand_3
weld_9.Part1 = rightHand_2
weld_9.Part0 = rightHand_3
rightUpperrArmMotor6d.Part0 = rootPart
rightUpperrArmMotor6d.Part1 = rightUpperrArm
rightUpperrArmMotor6d_2.Part1 = rightUpperrArm_2
weld_10.Part1 = rightUpperrArm
weld_10.Part0 = rightUpperrArm_2
rightUpperArmMotor6d.Part1 = rightUpperArm
weld_11.Part1 = rightUpperrArm_2
weld_11.Part0 = rightUpperArm
leftHandMotor6d.Part0 = rootPart
leftHandMotor6d.Part1 = leftHand
leftHandMotor6d_2.Part1 = leftHand_2
weld_12.Part1 = leftHand
weld_12.Part0 = leftHand_2
leftHandMotor6d_3.Part1 = leftHand_3
weld_13.Part1 = leftHand_2
weld_13.Part0 = leftHand_3
leftUpperArmMotor6d.Part0 = rootPart
leftUpperArmMotor6d.Part1 = leftUpperArm
leftUpperArmMotor6d_2.Part1 = leftUpperArm_2
weld_14.Part1 = leftUpperArm
weld_14.Part0 = leftUpperArm_2
leftUpperArmMotor6d_3.Part1 = leftUpperArm_3
weld_15.Part1 = leftUpperArm_2
weld_15.Part0 = leftUpperArm_3
rightLowerArmMotor6d.Part0 = rootPart
rightLowerArmMotor6d.Part1 = rightLowerArm
rightLowerArmMotor6d_2.Part1 = rightLowerArm_2
weld_16.Part1 = rightLowerArm
weld_16.Part0 = rightLowerArm_2
rightLowerArmMotor6d_3.Part1 = rightLowerArm_3
weld_17.Part1 = rightLowerArm_2
weld_17.Part0 = rightLowerArm_3

return ghastlyGlow
