local elevatorDoor, giantDoorBase, trapDoorL, wall_2, light, static, mastery, dandyStatic, pointLight, blackOverlay, pointLight_2, blackOverlay_2, dandyStaticPopup, masteryFrame, staticFrame, surfaceLight, trapDoorR, wall_5, elevator_2

local elevator = Instance.new("Model")
elevator.Name = "Elevator"
do
	local turnLightOn = Instance.new("Sound")
	turnLightOn.SoundId = "rbxassetid://7057058465"
	turnLightOn.Name = "TurnLightOn"
	turnLightOn.Volume = 0.3499
	turnLightOn.PlaybackSpeed = 0.8
	turnLightOn.RollOffMode = Enum.RollOffMode.InverseTapered
	turnLightOn.AudioContent = Content.fromUri("rbxassetid://7057058465")
	turnLightOn.Parent = elevator
	local buzz = Instance.new("Sound")
	buzz.SoundId = "rbxassetid://1103690959"
	buzz.Name = "Buzz"
	buzz.Volume = 0.3499
	buzz.RollOffMode = Enum.RollOffMode.InverseTapered
	buzz.AudioContent = Content.fromUri("rbxassetid://1103690959")
	buzz.Parent = elevator
	local part = Instance.new("Part")
	part.Anchored = true
	part.EnableFluidForces = false
	part.Size = Vector3.new(16.5041, 1, 11.7051)
	part.Material = Enum.Material.Neon
	part.TopSurface = Enum.SurfaceType.Smooth
	part.BottomSurface = Enum.SurfaceType.Smooth
	part.Color = Color3.fromRGB(0, 0, 0)
	part.CFrame = CFrame.new(Vector3.new(-746.7433, 96.7944, 111.9225))
	part.Parent = elevator
	local sounds = Instance.new("Part")
	sounds.Name = "Sounds"
	sounds.Transparency = 1
	sounds.CanQuery = false
	sounds.CanTouch = false
	sounds.Anchored = true
	sounds.EnableFluidForces = false
	sounds.CanCollide = false
	sounds.Size = Vector3.new(3.3085, 0.8271, 1.6542)
	sounds.BottomSurface = Enum.SurfaceType.Smooth
	sounds.TopSurface = Enum.SurfaceType.Smooth
	sounds.CFrame = CFrame.new(Vector3.new(-746.7682, 110.1867, 79.7763)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
	do
		local elevatorDing = Instance.new("Sound")
		elevatorDing.SoundId = "rbxassetid://9120327161"
		elevatorDing.Name = "ElevatorDing"
		elevatorDing.Volume = 0.25
		elevatorDing.RollOffMaxDistance = 200
		elevatorDing.PlaybackSpeed = 0.8999
		elevatorDing.RollOffMode = Enum.RollOffMode.Linear
		elevatorDing.AudioContent = Content.fromUri("rbxassetid://9120327161")
		elevatorDing.Parent = sounds
		local closing = Instance.new("Sound")
		closing.SoundId = "rbxassetid://4416840411"
		closing.Name = "Closing"
		closing.Volume = 0.18
		closing.RollOffMaxDistance = 200
		closing.RollOffMode = Enum.RollOffMode.Linear
		closing.AudioContent = Content.fromUri("rbxassetid://4416840411")
		closing.Parent = sounds
		local dirtSound = Instance.new("Sound")
		dirtSound.SoundId = "rbxassetid://7539892678"
		dirtSound.Name = "DirtSound"
		dirtSound.RollOffMaxDistance = 200
		dirtSound.RollOffMode = Enum.RollOffMode.Linear
		dirtSound.AudioContent = Content.fromUri("rbxassetid://7539892678")
		dirtSound.Parent = sounds
		local disruptSound = Instance.new("Sound")
		disruptSound.SoundId = "rbxassetid://6049670667"
		disruptSound.Name = "DisruptSound"
		disruptSound.RollOffMaxDistance = 200
		disruptSound.RollOffMode = Enum.RollOffMode.Linear
		disruptSound.AudioContent = Content.fromUri("rbxassetid://6049670667")
		disruptSound.Parent = sounds
		local metalGrind = Instance.new("Sound")
		metalGrind.SoundId = "rbxassetid://9125667610"
		metalGrind.Name = "MetalGrind"
		metalGrind.RollOffMaxDistance = 200
		metalGrind.RollOffMode = Enum.RollOffMode.Linear
		metalGrind.AudioContent = Content.fromUri("rbxassetid://9125667610")
		metalGrind.Parent = sounds
		local moveSound = Instance.new("Sound")
		moveSound.SoundId = "rbxassetid://6049670667"
		moveSound.Name = "MoveSound"
		moveSound.RollOffMaxDistance = 200
		moveSound.RollOffMode = Enum.RollOffMode.Linear
		moveSound.AudioContent = Content.fromUri("rbxassetid://6049670667")
		moveSound.Parent = sounds
		local opening = Instance.new("Sound")
		opening.SoundId = "rbxassetid://4694117632"
		opening.Name = "Opening"
		opening.Volume = 0.3
		opening.RollOffMaxDistance = 200
		opening.PlaybackSpeed = 0.6999
		opening.RollOffMode = Enum.RollOffMode.Linear
		opening.AudioContent = Content.fromUri("rbxassetid://4694117632")
		opening.Parent = sounds
		local placeSound = Instance.new("Sound")
		placeSound.SoundId = "rbxassetid://6049670667"
		placeSound.Name = "PlaceSound"
		placeSound.RollOffMaxDistance = 200
		placeSound.PlaybackSpeed = 0.6999
		placeSound.RollOffMode = Enum.RollOffMode.Linear
		placeSound.AudioContent = Content.fromUri("rbxassetid://6049670667")
		placeSound.Parent = sounds
		local closeSound = Instance.new("Sound")
		closeSound.SoundId = "rbxassetid://4228160116"
		closeSound.Name = "CloseSound"
		closeSound.RollOffMaxDistance = 200
		closeSound.PlaybackSpeed = 0.6999
		closeSound.RollOffMode = Enum.RollOffMode.Linear
		closeSound.AudioContent = Content.fromUri("rbxassetid://4228160116")
		closeSound.Parent = sounds
		local buzz2 = Instance.new("Sound")
		buzz2.SoundId = "rbxassetid://9112889325"
		buzz2.Name = "Buzz2"
		buzz2.RollOffMaxDistance = 250
		buzz2.Looped = true
		buzz2.RollOffMode = Enum.RollOffMode.InverseTapered
		buzz2.AudioContent = Content.fromUri("rbxassetid://9112889325")
		buzz2.Parent = sounds
	end
	sounds.Parent = elevator
	elevatorDoor = Instance.new("Model")
	elevatorDoor.Name = "ElevatorDoor"
	do
		local main = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://134361347068338", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		main.Name = "Main"
		main.CanTouch = false
		main.Anchored = true
		main.CanQuery = false
		main.AudioCanCollide = false
		main.CanCollide = false
		main.Size = Vector3.new(40.1511, 27.4186, 1.0207)
		main.CustomPhysicalProperties = PhysicalProperties.new(0, 0, 0, 0, 0, 0)
		main.Material = Enum.Material.DiamondPlate
		main.Color = Color3.fromRGB(104, 104, 104)
		main.CFrame = CFrame.new(Vector3.new(-747.08, 111.0158, 78.7668)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		main.PivotOffset = CFrame.identity
		main.Parent = elevatorDoor
		local stripes = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://84560013391977", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		stripes.Name = "Stripes"
		stripes.CanTouch = false
		stripes.Anchored = true
		stripes.AudioCanCollide = false
		stripes.CanQuery = false
		stripes.CanCollide = false
		stripes.Size = Vector3.new(39.1413, 26.3418, 1.5982)
		stripes.Color = Color3.fromRGB(255, 241, 133)
		stripes.CFrame = CFrame.new(Vector3.new(-746.8336, 110.8378, 78.7748)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		do
			local texture = Instance.new("Texture")
			texture.Texture = "rbxassetid://6794283750"
			texture.StudsPerTileU = 9
			texture.StudsPerTileV = 9
			texture.Transparency = 0.8999
			texture.Parent = stripes
			local texture_2 = Instance.new("Texture")
			texture_2.Texture = "rbxassetid://6794283750"
			texture_2.Transparency = 0.8999
			texture_2.StudsPerTileV = 9
			texture_2.StudsPerTileU = 9
			texture_2.Face = Enum.NormalId.Back
			texture_2.Parent = stripes
		end
		stripes.Parent = elevatorDoor
		local metalShort = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://77236853344385", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		metalShort.Name = "Metal_Short"
		metalShort.AudioCanCollide = false
		metalShort.CanTouch = false
		metalShort.Anchored = true
		metalShort.CanQuery = false
		metalShort.CanCollide = false
		metalShort.Size = Vector3.new(39.3619, 23.0174, 1.2796)
		metalShort.Material = Enum.Material.Concrete
		metalShort.Color = Color3.fromRGB(107, 107, 107)
		metalShort.CFrame = CFrame.new(Vector3.new(-747.0801, 109.5154, 78.716)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		metalShort.PivotOffset = CFrame.identity
		metalShort.Parent = elevatorDoor
		local metalMidLong = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://71233968054891", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		metalMidLong.Name = "Metal_Mid_Long"
		metalMidLong.CanTouch = false
		metalMidLong.AudioCanCollide = false
		metalMidLong.Anchored = true
		metalMidLong.CanCollide = false
		metalMidLong.CanQuery = false
		metalMidLong.Size = Vector3.new(40.3976, 4.5913, 1.3721)
		metalMidLong.Material = Enum.Material.Concrete
		metalMidLong.Color = Color3.fromRGB(107, 107, 107)
		metalMidLong.CFrame = CFrame.new(Vector3.new(-747.0801, 109.9302, 78.7047)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		metalMidLong.Parent = elevatorDoor
		local metalMidShort = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://96452337480349", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		metalMidShort.Name = "Metal_Mid_Short"
		metalMidShort.CanTouch = false
		metalMidShort.AudioCanCollide = false
		metalMidShort.Anchored = true
		metalMidShort.CanCollide = false
		metalMidShort.CanQuery = false
		metalMidShort.Size = Vector3.new(39.4599, 3.443, 1.4372)
		metalMidShort.Material = Enum.Material.DiamondPlate
		metalMidShort.Color = Color3.fromRGB(99, 95, 98)
		metalMidShort.CFrame = CFrame.new(Vector3.new(-746.9137, 109.9302, 78.6931)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		metalMidShort.Parent = elevatorDoor
		local metalLong = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://130393602416595", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		metalLong.Name = "Metal_Long"
		metalLong.CanTouch = false
		metalLong.AudioCanCollide = false
		metalLong.Anchored = true
		metalLong.CanCollide = false
		metalLong.CanQuery = false
		metalLong.Size = Vector3.new(39.6222, 22.9826, 1.1937)
		metalLong.Material = Enum.Material.DiamondPlate
		metalLong.Color = Color3.fromRGB(74, 74, 76)
		metalLong.CFrame = CFrame.new(Vector3.new(-747.08, 109.5154, 78.7077)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		metalLong.Parent = elevatorDoor
		giantDoorBase = Instance.new("Part")
		giantDoorBase.Name = "GiantDoorBase"
		giantDoorBase.Transparency = 1
		giantDoorBase.CanQuery = false
		giantDoorBase.CanTouch = false
		giantDoorBase.Anchored = true
		giantDoorBase.AudioCanCollide = false
		giantDoorBase.CanCollide = false
		giantDoorBase.Size = Vector3.new(0.2047, 22.9826, 12.5581)
		giantDoorBase.Material = Enum.Material.DiamondPlate
		giantDoorBase.BottomSurface = Enum.SurfaceType.Smooth
		giantDoorBase.TopSurface = Enum.SurfaceType.Smooth
		giantDoorBase.Color = Color3.fromRGB(74, 74, 76)
		giantDoorBase.CFrame = CFrame.new(Vector3.new(-747.1207, 109.1709, 78.1538)) * CFrame.fromEulerAnglesXYZ(0, math.rad(90), 0)
		giantDoorBase.Parent = elevatorDoor
	end
	elevatorDoor.Parent = elevator
	trapDoorL = Instance.new("Model")
	trapDoorL.Name = "TrapDoorL"
	do
		local wall = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16660675553", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
		wall.Name = "Wall"
		wall.Massless = true
		wall.Anchored = true
		wall.CanQuery = false
		wall.EnableFluidForces = false
		wall.Size = Vector3.new(8.093, 0.6089, 10.8)
		wall.Material = Enum.Material.Concrete
		wall.Color = Color3.fromRGB(107, 107, 107)
		wall.CFrame = CFrame.new(Vector3.new(-742.7507, 97.7912, 112.0799)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		wall.Parent = trapDoorL
		wall_2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16660679149", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
		wall_2.Name = "Wall"
		wall_2.Massless = true
		wall_2.Anchored = true
		wall_2.CanQuery = false
		wall_2.EnableFluidForces = false
		wall_2.Size = Vector3.new(0.9824, 1.0076, 10.8087)
		wall_2.Material = Enum.Material.Metal
		wall_2.Color = Color3.fromRGB(99, 95, 98)
		wall_2.CFrame = CFrame.new(Vector3.new(-738.7876, 97.8103, 112.0799)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		wall_2.Parent = trapDoorL
		local wall_3 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16660679868", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
		wall_3.Name = "Wall"
		wall_3.Massless = true
		wall_3.Anchored = true
		wall_3.CanQuery = false
		wall_3.EnableFluidForces = false
		wall_3.Size = Vector3.new(3.7366, 0.1071, 3.8285)
		wall_3.Material = Enum.Material.SmoothPlastic
		wall_3.Color = Color3.fromRGB(181, 162, 69)
		wall_3.CFrame = CFrame.new(Vector3.new(-742.6898, 97.9238, 112.0982))
		do
			local decal = Instance.new("Decal")
			decal.Texture = "rbxassetid://16660743178"
			decal.Face = Enum.NormalId.Top
			decal.Parent = wall_3
		end
		wall_3.Parent = trapDoorL
	end
	trapDoorL.Parent = elevator
	local buttonPanel = Instance.new("Model")
	buttonPanel.Name = "ButtonPanel"
	do
		local button = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://102709057276868", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		button.Name = "Button"
		button.Anchored = true
		button.Size = Vector3.new(0.1389, 6.9681, 2.3399)
		button.Material = Enum.Material.Metal
		button.Color = Color3.fromRGB(119, 119, 121)
		button.CFrame = CFrame.new(Vector3.new(-727.5499, 108.5464, 84.8218)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		button.PivotOffset = CFrame.new(Vector3.new(19.1895, -11.5769, -13.6427))
		button.Parent = buttonPanel
		local base02 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://111233840106390", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		base02.Name = "Base02"
		base02.Anchored = true
		base02.Size = Vector3.new(1.0632, 7.4593, 2.9427)
		base02.Material = Enum.Material.Concrete
		base02.CFrame = CFrame.new(Vector3.new(-727.072, 108.5941, 84.8199)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		base02.PivotOffset = CFrame.new(Vector3.new(19.6675, -11.6246, -13.6446))
		base02.Parent = buttonPanel
		local base01 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://121110160032121", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		base01.Name = "Base01"
		base01.Anchored = true
		base01.Size = Vector3.new(1.036, 7.9165, 3.4186)
		base01.Material = Enum.Material.WoodPlanks
		base01.Color = Color3.fromRGB(86, 66, 54)
		base01.CFrame = CFrame.new(Vector3.new(-727.0283, 108.5941, 84.8199)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		base01.PivotOffset = CFrame.new(Vector3.new(19.7112, -11.6246, -13.6446))
		base01.Parent = buttonPanel
	end
	buttonPanel.Parent = elevator
	local positions = Instance.new("Folder")
	positions.Name = "Positions"
	do
		local openTrapDoorL = Instance.new("Part")
		openTrapDoorL.Name = "OpenTrapDoorL"
		openTrapDoorL.Transparency = 1
		openTrapDoorL.CanCollide = false
		openTrapDoorL.Anchored = true
		openTrapDoorL.Size = Vector3.new(0.001, 0.1122, 0.0613)
		openTrapDoorL.BottomSurface = Enum.SurfaceType.Smooth
		openTrapDoorL.TopSurface = Enum.SurfaceType.Smooth
		openTrapDoorL.Material = Enum.Material.DiamondPlate
		openTrapDoorL.Color = Color3.fromRGB(74, 74, 76)
		openTrapDoorL.CFrame = CFrame.new(Vector3.new(-738.7876, 97.8103, 112.0799)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-90))
		openTrapDoorL.Parent = positions
		local dandyStoreOpen = Instance.new("Part")
		dandyStoreOpen.Name = "DandyStoreOpen"
		dandyStoreOpen.Transparency = 1
		dandyStoreOpen.CanCollide = false
		dandyStoreOpen.Anchored = true
		dandyStoreOpen.Size = Vector3.new(0.001, 0.1122, 0.0613)
		dandyStoreOpen.BottomSurface = Enum.SurfaceType.Smooth
		dandyStoreOpen.TopSurface = Enum.SurfaceType.Smooth
		dandyStoreOpen.Material = Enum.Material.DiamondPlate
		dandyStoreOpen.Color = Color3.fromRGB(74, 74, 76)
		dandyStoreOpen.CFrame = CFrame.new(Vector3.new(-746.7666, 97.6513, 112.1279))
		dandyStoreOpen.Parent = positions
		local dandyStoreClose = Instance.new("Part")
		dandyStoreClose.Name = "DandyStoreClose"
		dandyStoreClose.Transparency = 1
		dandyStoreClose.CanCollide = false
		dandyStoreClose.Anchored = true
		dandyStoreClose.Size = Vector3.new(0.001, 0.1122, 0.0613)
		dandyStoreClose.BottomSurface = Enum.SurfaceType.Smooth
		dandyStoreClose.TopSurface = Enum.SurfaceType.Smooth
		dandyStoreClose.Material = Enum.Material.DiamondPlate
		dandyStoreClose.Color = Color3.fromRGB(74, 74, 76)
		dandyStoreClose.CFrame = CFrame.new(Vector3.new(-746.7666, 87.9515, 112.1279))
		dandyStoreClose.Parent = positions
		local doorClose = Instance.new("Part")
		doorClose.Name = "DoorClose"
		doorClose.Transparency = 1
		doorClose.CanCollide = false
		doorClose.Anchored = true
		doorClose.Size = Vector3.new(0.001, 0.1122, 0.0613)
		doorClose.BottomSurface = Enum.SurfaceType.Smooth
		doorClose.TopSurface = Enum.SurfaceType.Smooth
		doorClose.Material = Enum.Material.DiamondPlate
		doorClose.Color = Color3.fromRGB(74, 74, 76)
		doorClose.CFrame = CFrame.new(Vector3.new(-747.1207, 109.1709, 78.1538)) * CFrame.fromEulerAnglesXYZ(0, math.rad(90), 0)
		doorClose.Parent = positions
		local doorOpen = Instance.new("Part")
		doorOpen.Name = "DoorOpen"
		doorOpen.Transparency = 1
		doorOpen.CanCollide = false
		doorOpen.Anchored = true
		doorOpen.Size = Vector3.new(0.001, 0.1122, 0.0613)
		doorOpen.BottomSurface = Enum.SurfaceType.Smooth
		doorOpen.TopSurface = Enum.SurfaceType.Smooth
		doorOpen.Material = Enum.Material.DiamondPlate
		doorOpen.Color = Color3.fromRGB(74, 74, 76)
		doorOpen.CFrame = CFrame.new(Vector3.new(-747.1207, 131.8964, 78.1538)) * CFrame.fromEulerAnglesXYZ(0, math.rad(90), 0)
		doorOpen.Parent = positions
		local closeTrapDoorL = Instance.new("Part")
		closeTrapDoorL.Name = "CloseTrapDoorL"
		closeTrapDoorL.Transparency = 1
		closeTrapDoorL.CanCollide = false
		closeTrapDoorL.Anchored = true
		closeTrapDoorL.Size = Vector3.new(0.001, 0.1122, 0.0613)
		closeTrapDoorL.BottomSurface = Enum.SurfaceType.Smooth
		closeTrapDoorL.TopSurface = Enum.SurfaceType.Smooth
		closeTrapDoorL.Material = Enum.Material.DiamondPlate
		closeTrapDoorL.Color = Color3.fromRGB(74, 74, 76)
		closeTrapDoorL.CFrame = CFrame.new(Vector3.new(-738.7876, 97.8103, 112.0799)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		closeTrapDoorL.Parent = positions
		local closeTrapDoorR = Instance.new("Part")
		closeTrapDoorR.Name = "CloseTrapDoorR"
		closeTrapDoorR.Transparency = 1
		closeTrapDoorR.CanCollide = false
		closeTrapDoorR.Anchored = true
		closeTrapDoorR.Size = Vector3.new(0.001, 0.1122, 0.0613)
		closeTrapDoorR.BottomSurface = Enum.SurfaceType.Smooth
		closeTrapDoorR.TopSurface = Enum.SurfaceType.Smooth
		closeTrapDoorR.Material = Enum.Material.DiamondPlate
		closeTrapDoorR.Color = Color3.fromRGB(74, 74, 76)
		closeTrapDoorR.CFrame = CFrame.new(Vector3.new(-754.7966, 97.8103, 112.0799))
		closeTrapDoorR.Parent = positions
		local openTrapDoorR = Instance.new("Part")
		openTrapDoorR.Name = "OpenTrapDoorR"
		openTrapDoorR.Transparency = 1
		openTrapDoorR.CanCollide = false
		openTrapDoorR.Anchored = true
		openTrapDoorR.Size = Vector3.new(0.001, 0.1122, 0.0613)
		openTrapDoorR.BottomSurface = Enum.SurfaceType.Smooth
		openTrapDoorR.TopSurface = Enum.SurfaceType.Smooth
		openTrapDoorR.Material = Enum.Material.DiamondPlate
		openTrapDoorR.Color = Color3.fromRGB(74, 74, 76)
		openTrapDoorR.CFrame = CFrame.new(Vector3.new(-754.7966, 97.8103, 112.0799)) * CFrame.fromEulerAnglesXYZ(0, 0, math.rad(90))
		openTrapDoorR.Parent = positions
	end
	positions.Parent = elevator
	local doorVisible = Instance.new("Part")
	doorVisible.Name = "DoorVisible"
	doorVisible.EnableFluidForces = false
	doorVisible.Anchored = true
	doorVisible.Size = Vector3.new(40.1511, 26.7695, 0.4441)
	doorVisible.BottomSurface = Enum.SurfaceType.Smooth
	doorVisible.Material = Enum.Material.Concrete
	doorVisible.TopSurface = Enum.SurfaceType.Smooth
	doorVisible.Color = Color3.fromRGB(107, 107, 107)
	doorVisible.CFrame = CFrame.new(Vector3.new(-747.1088, 110.6912, 78.9234))
	doorVisible.Parent = elevator
	local storeSounds = Instance.new("Part")
	storeSounds.Name = "StoreSounds"
	storeSounds.Transparency = 1
	storeSounds.CanQuery = false
	storeSounds.CanTouch = false
	storeSounds.Anchored = true
	storeSounds.EnableFluidForces = false
	storeSounds.CanCollide = false
	storeSounds.Size = Vector3.new(3.3085, 0.8271, 1.6542)
	storeSounds.BottomSurface = Enum.SurfaceType.Smooth
	storeSounds.TopSurface = Enum.SurfaceType.Smooth
	storeSounds.CFrame = CFrame.new(Vector3.new(-746.7682, 110.1867, 113.3769)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
	do
		local opening_2 = Instance.new("Sound")
		opening_2.SoundId = "rbxassetid://6431334087"
		opening_2.Name = "Opening"
		opening_2.Volume = 0.4
		opening_2.RollOffMaxDistance = 200
		opening_2.PlaybackSpeed = 1.5
		opening_2.RollOffMode = Enum.RollOffMode.Linear
		opening_2.AudioContent = Content.fromUri("rbxassetid://6431334087")
		opening_2.Parent = storeSounds
		local riseUp = Instance.new("Sound")
		riseUp.SoundId = "rbxassetid://7792922595"
		riseUp.Name = "RiseUp"
		riseUp.Volume = 0.3
		riseUp.RollOffMaxDistance = 200
		riseUp.RollOffMode = Enum.RollOffMode.Linear
		riseUp.AudioContent = Content.fromUri("rbxassetid://7792922595")
		riseUp.Parent = storeSounds
		local closing_2 = Instance.new("Sound")
		closing_2.SoundId = "rbxassetid://3908308607"
		closing_2.Name = "Closing"
		closing_2.Volume = 0.3
		closing_2.RollOffMaxDistance = 200
		closing_2.RollOffMode = Enum.RollOffMode.Linear
		closing_2.AudioContent = Content.fromUri("rbxassetid://3908308607")
		closing_2.Parent = storeSounds
		local switch = Instance.new("Sound")
		switch.SoundId = "rbxassetid://4416840411"
		switch.Name = "Switch"
		switch.Volume = 0.18
		switch.RollOffMaxDistance = 200
		switch.PlaybackSpeed = 1.5
		switch.RollOffMode = Enum.RollOffMode.Linear
		switch.AudioContent = Content.fromUri("rbxassetid://4416840411")
		switch.Parent = storeSounds
		local backDown = Instance.new("Sound")
		backDown.SoundId = "rbxassetid://9114304975"
		backDown.Name = "BackDown"
		backDown.Volume = 0.3
		backDown.RollOffMaxDistance = 200
		backDown.RollOffMode = Enum.RollOffMode.Linear
		backDown.AudioContent = Content.fromUri("rbxassetid://9114304975")
		backDown.Parent = storeSounds
	end
	storeSounds.Parent = elevator
	local base = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://123884400799566", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	base.Name = "Base"
	base.Anchored = true
	base.Size = Vector3.new(40, 1.0399, 40.4134)
	base.Material = Enum.Material.Concrete
	base.Color = Color3.fromRGB(248, 248, 248)
	base.CFrame = CFrame.new(Vector3.new(-746.7395, 96.9793, 98.463)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
	base.PivotOffset = CFrame.new(Vector3.new(0, -0.0098, -0.0015))
	do
		local texture_3 = Instance.new("Texture")
		texture_3.Texture = "rbxassetid://6794251647"
		texture_3.Transparency = 0.8999
		texture_3.StudsPerTileV = 8
		texture_3.StudsPerTileU = 8
		texture_3.Face = Enum.NormalId.Top
		texture_3.Parent = base
	end
	base.Parent = elevator
	local tvcart = Instance.new("Model")
	tvcart.Name = "TVCart"
	do
		local quickLinks = Instance.new("Folder")
		quickLinks.Name = "QuickLinks"
		do
			local disable = Instance.new("Folder")
			disable.Name = "Disable"
			do
				light = Instance.new("ObjectValue")
				light.Name = "Light"
				light.Parent = disable
				static = Instance.new("ObjectValue")
				static.Name = "Static"
				static.Parent = disable
				mastery = Instance.new("ObjectValue")
				mastery.Name = "Mastery"
				mastery.Parent = disable
				dandyStatic = Instance.new("ObjectValue")
				dandyStatic.Name = "DandyStatic"
				dandyStatic.Parent = disable
				pointLight = Instance.new("ObjectValue")
				pointLight.Name = "PointLight"
				pointLight.Parent = disable
				blackOverlay = Instance.new("ObjectValue")
				blackOverlay.Name = "BlackOverlay"
				blackOverlay.Parent = disable
			end
			disable.Parent = quickLinks
		end
		quickLinks.Parent = tvcart
		local screen = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://133684726338335", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		screen.Name = "Screen"
		screen.AudioCanCollide = false
		screen.Anchored = true
		screen.CanQuery = false
		screen.CanCollide = false
		screen.CanTouch = false
		screen.Size = Vector3.new(5.394, 3.5985, 0.2533)
		screen.CFrame = CFrame.new(Vector3.new(-760.72, 106.6776, 110.746))
		screen.PivotOffset = CFrame.identity
		do
			local attachment = Instance.new("Attachment")
			attachment.CFrame = CFrame.new(Vector3.new(0, 0, -2.7535))
			do
				pointLight_2 = Instance.new("PointLight")
				pointLight_2.Range = 6
				pointLight_2.Parent = attachment
			end
			attachment.Parent = screen
			local decal_2 = Instance.new("Decal")
			decal_2.Texture = "rbxassetid://88347757971552"
			decal_2.Transparency = 1
			decal_2.Parent = screen
			local surfaceGui = Instance.new("SurfaceGui")
			surfaceGui.LightInfluence = 1
			surfaceGui.MaxDistance = 1000
			surfaceGui.PixelsPerStud = 164.271
			surfaceGui.ClipsDescendants = true
			surfaceGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
			surfaceGui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
			do
				blackOverlay_2 = Instance.new("Frame")
				blackOverlay_2.Name = "BlackOverlay"
				blackOverlay_2.BorderSizePixel = 0
				blackOverlay_2.ZIndex = 5
				blackOverlay_2.AnchorPoint = Vector2.one * 0.5
				blackOverlay_2.Size = UDim2.fromScale(1, 1)
				blackOverlay_2.Position = UDim2.fromScale(0.5, 0.5)
				blackOverlay_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
				blackOverlay_2.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
				blackOverlay_2.BorderColor = BrickColor.new("Really black")
				blackOverlay_2.Parent = surfaceGui
				dandyStaticPopup = Instance.new("Frame")
				dandyStaticPopup.Name = "DandyStaticPopup"
				dandyStaticPopup.BorderSizePixel = 0
				dandyStaticPopup.BackgroundTransparency = 1
				dandyStaticPopup.ZIndex = 4
				dandyStaticPopup.Visible = false
				dandyStaticPopup.AnchorPoint = Vector2.one * 0.5
				dandyStaticPopup.Size = UDim2.fromScale(1, 1)
				dandyStaticPopup.Position = UDim2.fromScale(0.5, 0.5)
				dandyStaticPopup.BorderColor3 = Color3.fromRGB(0, 0, 0)
				dandyStaticPopup.BackgroundColor3 = Color3.fromRGB(121, 121, 121)
				dandyStaticPopup.BorderColor = BrickColor.new("Really black")
				do
					local dandyLogo = Instance.new("ImageLabel")
					dandyLogo.Name = "DandyLogo"
					dandyLogo.Image = "rbxassetid://114933170980660"
					dandyLogo.ImageTransparency = 0.3499
					dandyLogo.BackgroundTransparency = 1
					dandyLogo.AnchorPoint = Vector2.one * 0.5
					dandyLogo.Size = UDim2.fromScale(1, 1)
					dandyLogo.Position = UDim2.fromScale(0.5, 0.5)
					dandyLogo.BackgroundColor3 = Color3.fromRGB(28, 28, 40)
					dandyLogo.BorderColor3 = Color3.fromRGB(17, 17, 17)
					dandyLogo.BorderColor = BrickColor.new("Really black")
					dandyLogo.Parent = dandyStaticPopup
				end
				dandyStaticPopup.Parent = surfaceGui
				masteryFrame = Instance.new("Frame")
				masteryFrame.Name = "MasteryFrame"
				masteryFrame.BorderSizePixel = 0
				masteryFrame.BackgroundTransparency = 1
				masteryFrame.ZIndex = 3
				masteryFrame.Visible = false
				masteryFrame.AnchorPoint = Vector2.one * 0.5
				masteryFrame.Size = UDim2.fromScale(1, 1)
				masteryFrame.Position = UDim2.fromScale(0.5, 0.5)
				masteryFrame.BorderColor3 = Color3.fromRGB(0, 0, 0)
				masteryFrame.BackgroundColor3 = Color3.fromRGB(121, 121, 121)
				masteryFrame.BorderColor = BrickColor.new("Really black")
				do
					local frameBg = Instance.new("Frame")
					frameBg.Name = "FrameBG"
					frameBg.BorderSizePixel = 0
					frameBg.AnchorPoint = Vector2.one * 0.5
					frameBg.Size = UDim2.fromScale(1.0621, 1.0572)
					frameBg.Position = UDim2.fromScale(0.5, 0.5)
					frameBg.BorderColor3 = Color3.fromRGB(0, 0, 0)
					frameBg.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
					frameBg.BorderColor = BrickColor.new("Really black")
					do
						local uicorner = Instance.new("UICorner")
						uicorner.Parent = frameBg
					end
					frameBg.Parent = masteryFrame
					local textLabel = Instance.new("TextLabel")
					textLabel.Text = "MASTERY"
					textLabel.BorderSizePixel = 0
					textLabel.TextSize = 14
					textLabel.ZIndex = 6
					textLabel.TextStrokeTransparency = 0
					textLabel.TextScaled = true
					textLabel.TextWrapped = true
					textLabel.RichText = true
					textLabel.Size = UDim2.fromScale(1.0439, 0.1002)
					textLabel.Position = UDim2.fromScale(-0.0201, -0.1003)
					textLabel.FontFace = Font.fromName("FredokaOne")
					textLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
					textLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
					textLabel.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
					textLabel.BorderColor = BrickColor.new("Really black")
					do
						local uicorner_2 = Instance.new("UICorner")
						uicorner_2.Parent = textLabel
					end
					textLabel.Parent = masteryFrame
					local holderFrame = Instance.new("Frame")
					holderFrame.Name = "HolderFrame"
					holderFrame.BackgroundTransparency = 0.6499
					holderFrame.ZIndex = 6
					holderFrame.BorderSizePixel = 0
					holderFrame.AnchorPoint = Vector2.one * 0.5
					holderFrame.Size = UDim2.fromScale(0.9119, 0.5143)
					holderFrame.Position = UDim2.fromScale(0.4982, 0.2982)
					holderFrame.BorderColor3 = Color3.fromRGB(0, 0, 0)
					holderFrame.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
					holderFrame.BorderColor = BrickColor.new("Really black")
					do
						local uigradient = Instance.new("UIGradient")
						uigradient.Rotation = 90
						uigradient.Color = ColorSequence.new(Color3.fromRGB(140, 140, 140), Color3.fromRGB(81, 81, 81))
						uigradient.Parent = holderFrame
						local uicorner_3 = Instance.new("UICorner")
						uicorner_3.Parent = holderFrame
						local template = Instance.new("TextButton")
						template.Text = " "
						template.Name = "Template"
						template.TextSize = 14
						template.BackgroundTransparency = 1
						template.ZIndex = 12
						template.BorderSizePixel = 0
						template.Visible = false
						template.Position = UDim2.fromScale(0, 0)
						template.Size = UDim2.fromScale(0.5, 0.2)
						template.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
						template.BorderColor3 = Color3.fromRGB(0, 0, 0)
						template.TextColor3 = Color3.fromRGB(0, 0, 0)
						template.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
						template.BorderColor = BrickColor.new("Really black")
						do
							local frame = Instance.new("Frame")
							frame.ZIndex = 2
							frame.BorderSizePixel = 0
							frame.AnchorPoint = Vector2.one * 0.5
							frame.Position = UDim2.fromScale(0.4989, 0.4961)
							frame.Size = UDim2.fromScale(0.8397, 0.8397)
							frame.BackgroundColor3 = Color3.fromRGB(121, 121, 121)
							frame.BorderColor3 = Color3.fromRGB(0, 0, 0)
							frame.BorderColor = BrickColor.new("Really black")
							do
								local uigradient_2 = Instance.new("UIGradient")
								uigradient_2.Rotation = 90
								uigradient_2.Color = ColorSequence.new(Color3.fromRGB(140, 140, 140), Color3.fromRGB(81, 81, 81))
								uigradient_2.Parent = frame
								local uicorner_4 = Instance.new("UICorner")
								uicorner_4.Parent = frame
							end
							frame.Parent = template
							local frameBg_2 = Instance.new("Frame")
							frameBg_2.Name = "FrameBG"
							frameBg_2.BorderSizePixel = 0
							frameBg_2.AnchorPoint = Vector2.one * 0.5
							frameBg_2.Size = UDim2.fromScale(0.9344, 0.9636)
							frameBg_2.Position = UDim2.fromScale(0.4989, 0.4961)
							frameBg_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
							frameBg_2.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
							frameBg_2.BorderColor = BrickColor.new("Really black")
							do
								local uicorner_5 = Instance.new("UICorner")
								uicorner_5.Parent = frameBg_2
							end
							frameBg_2.Parent = template
							local characterName = Instance.new("TextLabel")
							characterName.Text = "Do this thing like 3 times"
							characterName.Name = "CharacterName"
							characterName.TextSize = 14
							characterName.BorderSizePixel = 0
							characterName.TextStrokeTransparency = 0
							characterName.ZIndex = 13
							characterName.BackgroundTransparency = 1
							characterName.TextWrapped = true
							characterName.TextScaled = true
							characterName.Size = UDim2.fromScale(0.8397, 0.4039)
							characterName.Position = UDim2.fromScale(0.079, 0.0762)
							characterName.FontFace = Font.fromName("FredokaOne")
							characterName.BorderColor3 = Color3.fromRGB(0, 0, 0)
							characterName.TextColor3 = Color3.fromRGB(255, 255, 255)
							characterName.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
							characterName.BorderColor = BrickColor.new("Really black")
							characterName.Parent = template
							local maxFill = Instance.new("Frame")
							maxFill.Name = "MaxFill"
							maxFill.BorderSizePixel = 0
							maxFill.ZIndex = 10
							maxFill.Position = UDim2.fromScale(0.1304, 0.5639)
							maxFill.Size = UDim2.fromScale(0.7364, 0.2742)
							maxFill.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
							maxFill.BorderColor3 = Color3.fromRGB(0, 0, 0)
							maxFill.BorderColor = BrickColor.new("Really black")
							do
								local uicorner_6 = Instance.new("UICorner")
								uicorner_6.Parent = maxFill
								local currentFill = Instance.new("Frame")
								currentFill.Name = "CurrentFill"
								currentFill.BorderSizePixel = 0
								currentFill.ZIndex = 2
								currentFill.Size = UDim2.fromScale(0, 1)
								currentFill.BackgroundColor3 = Color3.fromRGB(141, 141, 141)
								currentFill.BorderColor3 = Color3.fromRGB(0, 0, 0)
								currentFill.BorderColor = BrickColor.new("Really black")
								do
									local uicorner_7 = Instance.new("UICorner")
									uicorner_7.Parent = currentFill
								end
								currentFill.Parent = maxFill
							end
							maxFill.Parent = template
							local characterAmount = Instance.new("TextLabel")
							characterAmount.Text = "1/1"
							characterAmount.Name = "CharacterAmount"
							characterAmount.TextSize = 14
							characterAmount.BorderSizePixel = 0
							characterAmount.TextStrokeTransparency = 0
							characterAmount.ZIndex = 16
							characterAmount.BackgroundTransparency = 1
							characterAmount.TextWrapped = true
							characterAmount.TextScaled = true
							characterAmount.Size = UDim2.fromScale(0.7364, 0.2687)
							characterAmount.Position = UDim2.fromScale(0.1304, 0.5639)
							characterAmount.FontFace = Font.fromName("FredokaOne")
							characterAmount.BorderColor3 = Color3.fromRGB(0, 0, 0)
							characterAmount.TextColor3 = Color3.fromRGB(255, 255, 255)
							characterAmount.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
							characterAmount.BorderColor = BrickColor.new("Really black")
							characterAmount.Parent = template
						end
						template.Parent = holderFrame
						local uigridLayout = Instance.new("UIGridLayout")
						uigridLayout.CellPadding = UDim2.new(0, 0)
						uigridLayout.CellSize = UDim2.fromScale(0.5, 0.4499)
						uigridLayout.Parent = holderFrame
					end
					holderFrame.Parent = masteryFrame
					local exitButton = Instance.new("TextButton")
					exitButton.Text = " "
					exitButton.Name = "ExitButton"
					exitButton.TextSize = 14
					exitButton.BackgroundTransparency = 1
					exitButton.ZIndex = 15
					exitButton.BorderSizePixel = 0
					exitButton.Visible = false
					exitButton.Position = UDim2.fromScale(0.2704, 1.0455)
					exitButton.Size = UDim2.fromScale(0.4581, 0.1077)
					exitButton.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
					exitButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
					exitButton.TextColor3 = Color3.fromRGB(0, 0, 0)
					exitButton.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
					exitButton.BorderColor = BrickColor.new("Really black")
					do
						local frame_2 = Instance.new("Frame")
						frame_2.ZIndex = 2
						frame_2.BorderSizePixel = 0
						frame_2.AnchorPoint = Vector2.one * 0.5
						frame_2.Position = UDim2.fromScale(0.5, 0.5)
						frame_2.Size = UDim2.fromScale(0.906, 0.8397)
						frame_2.BackgroundColor3 = Color3.fromRGB(255, 106, 108)
						frame_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
						frame_2.BorderColor = BrickColor.new("Really black")
						do
							local uicorner_8 = Instance.new("UICorner")
							uicorner_8.Parent = frame_2
							local uigradient_3 = Instance.new("UIGradient")
							uigradient_3.Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(191, 124, 125)), ColorSequenceKeypoint.new(0.2797, Color3.fromRGB(251, 252, 251)), ColorSequenceKeypoint.new(0.7219, Color3.fromRGB(255, 255, 255)), ColorSequenceKeypoint.new(1, Color3.fromRGB(191, 124, 125))})
							uigradient_3.Parent = frame_2
						end
						frame_2.Parent = exitButton
						local frameBg_3 = Instance.new("Frame")
						frameBg_3.Name = "FrameBG"
						frameBg_3.BorderSizePixel = 0
						frameBg_3.AnchorPoint = Vector2.one * 0.5
						frameBg_3.Size = UDim2.fromScale(0.9957, 1.0898)
						frameBg_3.Position = UDim2.fromScale(0.5, 0.4963)
						frameBg_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
						frameBg_3.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
						frameBg_3.BorderColor = BrickColor.new("Really black")
						do
							local uicorner_9 = Instance.new("UICorner")
							uicorner_9.Parent = frameBg_3
						end
						frameBg_3.Parent = exitButton
						local characterName_2 = Instance.new("TextLabel")
						characterName_2.Text = "EXIT"
						characterName_2.Name = "CharacterName"
						characterName_2.TextSize = 14
						characterName_2.BorderSizePixel = 0
						characterName_2.ZIndex = 13
						characterName_2.BackgroundTransparency = 1
						characterName_2.TextWrapped = true
						characterName_2.TextScaled = true
						characterName_2.Size = UDim2.fromScale(0.8395, 0.8397)
						characterName_2.Position = UDim2.fromScale(0.079, 0.0762)
						characterName_2.FontFace = Font.fromName("FredokaOne")
						characterName_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
						characterName_2.TextColor3 = Color3.fromRGB(127, 48, 49)
						characterName_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
						characterName_2.BorderColor = BrickColor.new("Really black")
						characterName_2.Parent = exitButton
					end
					exitButton.Parent = masteryFrame
					local maxLoad = Instance.new("Frame")
					maxLoad.Name = "MaxLoad"
					maxLoad.ZIndex = 10
					maxLoad.Size = UDim2.fromScale(0.8782, 0.0841)
					maxLoad.Position = UDim2.fromScale(0.0596, 0.8201)
					maxLoad.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
					do
						local uicorner_10 = Instance.new("UICorner")
						uicorner_10.Parent = maxLoad
						local currentLoad = Instance.new("Frame")
						currentLoad.Name = "CurrentLoad"
						currentLoad.ZIndex = 11
						currentLoad.Size = UDim2.fromScale(0, 1)
						currentLoad.BackgroundColor3 = Color3.fromRGB(141, 141, 141)
						do
							local uigradient_4 = Instance.new("UIGradient")
							uigradient_4.Color = ColorSequence.new(Color3.fromRGB(255, 255, 255), Color3.fromRGB(176, 176, 176))
							uigradient_4.Parent = currentLoad
						end
						currentLoad.Parent = maxLoad
					end
					maxLoad.Parent = masteryFrame
					local maxLoadBg = Instance.new("Frame")
					maxLoadBg.Name = "MaxLoadBG"
					maxLoadBg.ZIndex = 9
					maxLoadBg.Size = UDim2.fromScale(0.908, 0.105)
					maxLoadBg.Position = UDim2.fromScale(0.0415, 0.8094)
					maxLoadBg.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
					do
						local uicorner_11 = Instance.new("UICorner")
						uicorner_11.Parent = maxLoadBg
					end
					maxLoadBg.Parent = masteryFrame
					local lines = Instance.new("Folder")
					lines.Name = "Lines"
					do
						local line = Instance.new("Frame")
						line.Name = "Line"
						line.ZIndex = 12
						line.Size = UDim2.fromScale(0.0117, 0.0923)
						line.Position = UDim2.fromScale(0.1939, 0.8153)
						line.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
						do
							local uicorner_12 = Instance.new("UICorner")
							uicorner_12.Parent = line
						end
						line.Parent = lines
						local line_2 = Instance.new("Frame")
						line_2.Name = "Line"
						line_2.ZIndex = 12
						line_2.Size = UDim2.fromScale(0.0117, 0.0923)
						line_2.Position = UDim2.fromScale(0.3393, 0.8153)
						line_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
						do
							local uicorner_13 = Instance.new("UICorner")
							uicorner_13.Parent = line_2
						end
						line_2.Parent = lines
						local line_3 = Instance.new("Frame")
						line_3.Name = "Line"
						line_3.ZIndex = 12
						line_3.Size = UDim2.fromScale(0.0117, 0.0923)
						line_3.Position = UDim2.fromScale(0.494, 0.8153)
						line_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
						do
							local uicorner_14 = Instance.new("UICorner")
							uicorner_14.Parent = line_3
						end
						line_3.Parent = lines
						local line_4 = Instance.new("Frame")
						line_4.Name = "Line"
						line_4.ZIndex = 12
						line_4.Size = UDim2.fromScale(0.0117, 0.0923)
						line_4.Position = UDim2.fromScale(0.6441, 0.8153)
						line_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
						do
							local uicorner_15 = Instance.new("UICorner")
							uicorner_15.Parent = line_4
						end
						line_4.Parent = lines
						local line_5 = Instance.new("Frame")
						line_5.Name = "Line"
						line_5.ZIndex = 12
						line_5.Size = UDim2.fromScale(0.0117, 0.0923)
						line_5.Position = UDim2.fromScale(0.791, 0.8153)
						line_5.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
						do
							local uicorner_16 = Instance.new("UICorner")
							uicorner_16.Parent = line_5
						end
						line_5.Parent = lines
					end
					lines.Parent = masteryFrame
					local frame_3 = Instance.new("Frame")
					frame_3.ZIndex = 2
					frame_3.BorderSizePixel = 0
					frame_3.Visible = false
					frame_3.AnchorPoint = Vector2.one * 0.5
					frame_3.Size = UDim2.fromScale(1, 1)
					frame_3.Position = UDim2.fromScale(0.5, 0.5)
					frame_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
					frame_3.BackgroundColor3 = Color3.fromRGB(121, 121, 121)
					frame_3.BorderColor = BrickColor.new("Really black")
					do
						local uigradient_5 = Instance.new("UIGradient")
						uigradient_5.Rotation = 90
						uigradient_5.Color = ColorSequence.new(Color3.fromRGB(140, 140, 140), Color3.fromRGB(81, 81, 81))
						uigradient_5.Parent = frame_3
						local uicorner_17 = Instance.new("UICorner")
						uicorner_17.Parent = frame_3
						local imageLabel = Instance.new("ImageLabel")
						imageLabel.Image = "rbxassetid://6794283750"
						imageLabel.ImageTransparency = 0.98
						imageLabel.BorderSizePixel = 0
						imageLabel.BackgroundTransparency = 1
						imageLabel.TileSize = UDim2.fromScale(0.25, 1)
						imageLabel.Size = UDim2.fromScale(1, 1)
						imageLabel.ScaleType = Enum.ScaleType.Tile
						imageLabel.BorderColor3 = Color3.fromRGB(0, 0, 0)
						imageLabel.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
						imageLabel.BorderColor = BrickColor.new("Really black")
						imageLabel.Parent = frame_3
					end
					frame_3.Parent = masteryFrame
					local claimReward = Instance.new("TextButton")
					claimReward.Text = " "
					claimReward.Name = "ClaimReward"
					claimReward.TextSize = 14
					claimReward.BackgroundTransparency = 1
					claimReward.ZIndex = 15
					claimReward.BorderSizePixel = 0
					claimReward.Visible = false
					claimReward.Position = UDim2.fromScale(0.3424, 0.9249)
					claimReward.Size = UDim2.fromScale(0.3156, 0.0678)
					claimReward.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json")
					claimReward.BorderColor3 = Color3.fromRGB(0, 0, 0)
					claimReward.TextColor3 = Color3.fromRGB(0, 0, 0)
					claimReward.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
					claimReward.BorderColor = BrickColor.new("Really black")
					do
						local frameBg_4 = Instance.new("Frame")
						frameBg_4.Name = "FrameBG"
						frameBg_4.BorderSizePixel = 0
						frameBg_4.AnchorPoint = Vector2.one * 0.5
						frameBg_4.Size = UDim2.fromScale(0.952, 0.9818)
						frameBg_4.Position = UDim2.fromScale(0.5, 0.5)
						frameBg_4.BorderColor3 = Color3.fromRGB(0, 0, 0)
						frameBg_4.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
						frameBg_4.BorderColor = BrickColor.new("Really black")
						do
							local uicorner_18 = Instance.new("UICorner")
							uicorner_18.Parent = frameBg_4
						end
						frameBg_4.Parent = claimReward
						local characterName_3 = Instance.new("TextLabel")
						characterName_3.Text = "CLAIM!"
						characterName_3.Name = "CharacterName"
						characterName_3.TextSize = 14
						characterName_3.BorderSizePixel = 0
						characterName_3.ZIndex = 13
						characterName_3.BackgroundTransparency = 1
						characterName_3.TextWrapped = true
						characterName_3.TextScaled = true
						characterName_3.Size = UDim2.fromScale(0.8094, 0.8397)
						characterName_3.Position = UDim2.fromScale(0.079, 0.0762)
						characterName_3.FontFace = Font.fromName("FredokaOne")
						characterName_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
						characterName_3.TextColor3 = Color3.fromRGB(65, 127, 70)
						characterName_3.BorderColor3 = Color3.fromRGB(0, 0, 0)
						characterName_3.BorderColor = BrickColor.new("Really black")
						characterName_3.Parent = claimReward
						local frame_4 = Instance.new("Frame")
						frame_4.ZIndex = 2
						frame_4.BorderSizePixel = 0
						frame_4.AnchorPoint = Vector2.one * 0.5
						frame_4.Position = UDim2.fromScale(0.5, 0.5)
						frame_4.Size = UDim2.fromScale(0.906, 0.8397)
						frame_4.BackgroundColor3 = Color3.fromRGB(131, 255, 135)
						frame_4.BorderColor3 = Color3.fromRGB(0, 0, 0)
						frame_4.BorderColor = BrickColor.new("Really black")
						do
							local uicorner_19 = Instance.new("UICorner")
							uicorner_19.Parent = frame_4
							local uigradient_6 = Instance.new("UIGradient")
							uigradient_6.Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(150, 191, 149)), ColorSequenceKeypoint.new(0.2797, Color3.fromRGB(251, 252, 251)), ColorSequenceKeypoint.new(0.7219, Color3.fromRGB(255, 255, 255)), ColorSequenceKeypoint.new(1, Color3.fromRGB(150, 191, 149))})
							uigradient_6.Parent = frame_4
						end
						frame_4.Parent = claimReward
					end
					claimReward.Parent = masteryFrame
					local completedText = Instance.new("TextLabel")
					completedText.Name = "CompletedText"
					completedText.Text = "REACH 100% MASTERY TO UNLOCK A SKIN!"
					completedText.TextSize = 14
					completedText.BorderSizePixel = 0
					completedText.TextStrokeTransparency = 0
					completedText.ZIndex = 6
					completedText.BackgroundTransparency = 1
					completedText.TextWrapped = true
					completedText.TextScaled = true
					completedText.RichText = true
					completedText.Size = UDim2.fromScale(0.9206, 0.0638)
					completedText.Position = UDim2.fromScale(0.0333, 0.7365)
					completedText.FontFace = Font.fromName("FredokaOne")
					completedText.BorderColor3 = Color3.fromRGB(0, 0, 0)
					completedText.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
					completedText.TextColor3 = Color3.fromRGB(255, 255, 255)
					completedText.BorderColor = BrickColor.new("Really black")
					do
						local uicorner_20 = Instance.new("UICorner")
						uicorner_20.Parent = completedText
					end
					completedText.Parent = masteryFrame
				end
				masteryFrame.Parent = surfaceGui
				staticFrame = Instance.new("Frame")
				staticFrame.Name = "StaticFrame"
				staticFrame.BorderSizePixel = 0
				staticFrame.BackgroundTransparency = 1
				staticFrame.ZIndex = 5
				staticFrame.Visible = false
				staticFrame.AnchorPoint = Vector2.one * 0.5
				staticFrame.Size = UDim2.fromScale(1, 1)
				staticFrame.Position = UDim2.fromScale(0.5, 0.5)
				staticFrame.BorderColor3 = Color3.fromRGB(0, 0, 0)
				staticFrame.BackgroundColor3 = Color3.fromRGB(121, 121, 121)
				staticFrame.BorderColor = BrickColor.new("Really black")
				do
					local staticframe = Instance.new("ImageLabel")
					staticframe.Image = "http://www.roblox.com/asset/?id=4388381112"
					staticframe.Name = "staticframe"
					staticframe.BackgroundTransparency = 1
					staticframe.ImageTransparency = 0.74
					staticframe.ZIndex = -1
					staticframe.AnchorPoint = Vector2.one * 0.5
					staticframe.Size = UDim2.fromScale(1, 1)
					staticframe.Position = UDim2.fromScale(0.5, 0.5)
					staticframe.BorderColor3 = Color3.fromRGB(17, 17, 17)
					staticframe.BackgroundColor3 = Color3.fromRGB(28, 28, 40)
					staticframe.BorderColor = BrickColor.new("Really black")
					do
						local staticScript = Instance.new("Script")
						staticScript.Name = "static script"
						staticScript.Parent = staticframe
						local staticScriptLocal = Instance.new("LocalScript")
						staticScriptLocal.Name = "StaticScript_Local"
						staticScriptLocal.Disabled = true
						staticScriptLocal.Enabled = false
						staticScriptLocal.Parent = staticframe
					end
					staticframe.Parent = staticFrame
				end
				staticFrame.Parent = surfaceGui
			end
			surfaceGui.Parent = screen
			surfaceLight = Instance.new("SurfaceLight")
			surfaceLight.Brightness = 1.1399
			surfaceLight.Enabled = false
			surfaceLight.Color = Color3.fromRGB(79, 79, 79)
			surfaceLight.Parent = screen
		end
		screen.Parent = tvcart
		local tv = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://136630390265181", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		tv.TextureID = "rbxassetid://93379736309235"
		tv.Name = "TV"
		tv.CanTouch = false
		tv.Anchored = true
		tv.AudioCanCollide = false
		tv.CanQuery = false
		tv.CanCollide = false
		tv.Size = Vector3.new(6.8637, 7.0516, 2.7663)
		tv.CFrame = CFrame.new(Vector3.new(-760.7201, 105.5922, 111.8168))
		tv.PivotOffset = CFrame.identity
		tv.Parent = tvcart
		local cart = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://100019719560092", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		cart.TextureID = "rbxassetid://93379736309235"
		cart.Name = "Cart"
		cart.CanTouch = false
		cart.Anchored = true
		cart.AudioCanCollide = false
		cart.CanQuery = false
		cart.CanCollide = false
		cart.Size = Vector3.new(7.9251, 7.4946, 5.3874)
		cart.CFrame = CFrame.new(Vector3.new(-760.7201, 100.9726, 111.8168))
		cart.PivotOffset = CFrame.identity
		cart.Parent = tvcart
		local wire02 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://115660837275240", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		wire02.TextureID = "rbxassetid://93379736309235"
		wire02.Name = "Wire02"
		wire02.CanTouch = false
		wire02.Anchored = true
		wire02.CanQuery = false
		wire02.CanCollide = false
		wire02.AudioCanCollide = false
		wire02.Size = Vector3.new(2.5421, 8.8435, 11.0523)
		wire02.CFrame = CFrame.new(Vector3.new(-761.7852, 101.8835, 118.5178))
		wire02.Parent = tvcart
		local noClip = Instance.new("Part")
		noClip.Name = "NoClip"
		noClip.Transparency = 1
		noClip.Anchored = true
		noClip.Size = Vector3.new(9.5168, 12.174, 8.5238)
		noClip.BottomSurface = Enum.SurfaceType.Smooth
		noClip.Material = Enum.Material.Neon
		noClip.TopSurface = Enum.SurfaceType.Smooth
		noClip.Color = Color3.fromRGB(255, 0, 0)
		noClip.CFrame = CFrame.new(Vector3.new(-761.7804, 103.0009, 112.9198)) * CFrame.fromEulerAnglesXYZ(0, math.rad(-8.0288), 0)
		do
			local static_2 = Instance.new("Sound")
			static_2.SoundId = "rbxassetid://372770465"
			static_2.Name = "Static"
			static_2.Volume = 0.025
			static_2.RollOffMinDistance = 10.5436
			static_2.RollOffMaxDistance = 10543.6562
			static_2.Looped = true
			static_2.AudioContent = Content.fromUri("rbxassetid://372770465")
			static_2.Parent = noClip
			local staticGlitch = Instance.new("Sound")
			staticGlitch.SoundId = "rbxassetid://6896112317"
			staticGlitch.Name = "StaticGlitch"
			staticGlitch.RollOffMinDistance = 10.5436
			staticGlitch.Volume = 0.3499
			staticGlitch.RollOffMaxDistance = 10543.6562
			staticGlitch.AudioContent = Content.fromUri("rbxassetid://6896112317")
			staticGlitch.Parent = noClip
			local tvclick = Instance.new("Sound")
			tvclick.SoundId = "rbxassetid://9114213410"
			tvclick.Name = "TVClick"
			tvclick.RollOffMinDistance = 10.5436
			tvclick.Volume = 0.25
			tvclick.RollOffMaxDistance = 10543.6562
			tvclick.AudioContent = Content.fromUri("rbxassetid://9114213410")
			tvclick.Parent = noClip
			local startup = Instance.new("Sound")
			startup.SoundId = "rbxassetid://79181889421030"
			startup.Name = "Startup"
			startup.RollOffMinDistance = 10.5436
			startup.Volume = 0
			startup.RollOffMaxDistance = 10543.6562
			startup.AudioContent = Content.fromUri("rbxassetid://79181889421030")
			startup.Parent = noClip
			local turnOff = Instance.new("Sound")
			turnOff.SoundId = "rbxassetid://119684909702342"
			turnOff.Name = "TurnOff"
			turnOff.RollOffMinDistance = 10.5436
			turnOff.Volume = 0.25
			turnOff.RollOffMaxDistance = 10543.6562
			turnOff.AudioContent = Content.fromUri("rbxassetid://119684909702342")
			turnOff.Parent = noClip
		end
		noClip.Parent = tvcart
	end
	tvcart.Parent = elevator
	local walls = Instance.new("Model")
	walls.Name = "Walls"
	do
		local accent01 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://103180644642358", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		accent01.Name = "Accent01"
		accent01.AudioCanCollide = false
		accent01.CanTouch = false
		accent01.Anchored = true
		accent01.CanQuery = false
		accent01.CanCollide = false
		accent01.Size = Vector3.new(40.5519, 26.7422, 39.9278)
		accent01.Material = Enum.Material.Concrete
		accent01.CFrame = CFrame.new(Vector3.new(-746.5207, 110.2853, 98.7229)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		accent01.PivotOffset = CFrame.new(Vector3.new(0, -13.3158, 0.2584))
		accent01.Parent = walls
		local top = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://98243777050191", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		top.Name = "Top"
		top.AudioCanCollide = false
		top.CanTouch = false
		top.Anchored = true
		top.CanQuery = false
		top.CanCollide = false
		top.Size = Vector3.new(40.8603, 26.8243, 40.4169)
		top.Material = Enum.Material.Wood
		top.Color = Color3.fromRGB(124, 92, 70)
		top.CFrame = CFrame.new(Vector3.new(-746.6301, 109.9941, 99.0011)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		top.PivotOffset = CFrame.new(Vector3.new(-0.1094, -13.0246, 0.5366))
		top.Parent = walls
		local accent02 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://94514593786637", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		accent02.Name = "Accent02"
		accent02.AudioCanCollide = false
		accent02.CanTouch = false
		accent02.Anchored = true
		accent02.CanQuery = false
		accent02.CanCollide = false
		accent02.Size = Vector3.new(40.6056, 28.3899, 37.665)
		accent02.Material = Enum.Material.DiamondPlate
		accent02.Color = Color3.fromRGB(99, 95, 98)
		accent02.CFrame = CFrame.new(Vector3.new(-746.6301, 109.0655, 100.2497)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		accent02.PivotOffset = CFrame.new(Vector3.new(-0.1094, -12.096, 1.7852))
		accent02.Parent = walls
		local bottom = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://103757156216165", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		bottom.Name = "Bottom"
		bottom.AudioCanCollide = false
		bottom.CanTouch = false
		bottom.Anchored = true
		bottom.CanQuery = false
		bottom.CanCollide = false
		bottom.Size = Vector3.new(40.7194, 6.4713, 36.9334)
		bottom.Material = Enum.Material.Wood
		bottom.Color = Color3.fromRGB(86, 66, 54)
		bottom.CFrame = CFrame.new(Vector3.new(-746.6301, 100.9193, 100.6723)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		bottom.PivotOffset = CFrame.new(Vector3.new(-0.1094, -3.9497, 2.2079))
		bottom.Parent = walls
		local edgeBottom = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://116204073853261", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		edgeBottom.Name = "Edge_Bottom"
		edgeBottom.AudioCanCollide = false
		edgeBottom.CanTouch = false
		edgeBottom.Anchored = true
		edgeBottom.CanQuery = false
		edgeBottom.CanCollide = false
		edgeBottom.Size = Vector3.new(39.1457, 1.6245, 36.4813)
		edgeBottom.Color = Color3.fromRGB(0, 0, 0)
		edgeBottom.CFrame = CFrame.new(Vector3.new(-746.7395, 98.0296, 100.4461)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		edgeBottom.PivotOffset = CFrame.new(Vector3.new(19.2072, 0.0059, 0))
		edgeBottom.Parent = walls
		local edgeFront = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://103849942008847", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
		edgeFront.Name = "Edge_Front"
		edgeFront.AudioCanCollide = false
		edgeFront.CanTouch = false
		edgeFront.Anchored = true
		edgeFront.CanQuery = false
		edgeFront.CanCollide = false
		edgeFront.Size = Vector3.new(40.0356, 1.6245, 3.461)
		edgeFront.Material = Enum.Material.DiamondPlate
		edgeFront.Color = Color3.fromRGB(0, 0, 0)
		edgeFront.CFrame = CFrame.new(Vector3.new(-746.6301, 98.0296, 80.4762)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		edgeFront.PivotOffset = CFrame.new(Vector3.new(19.3935, 0.0059, -14.0485))
		edgeFront.Parent = walls
		local wallCollider = Instance.new("Part")
		wallCollider.Name = "WallCollider"
		wallCollider.Transparency = 1
		wallCollider.Anchored = true
		wallCollider.Size = Vector3.new(2.6824, 29.7859, 41.4639)
		wallCollider.BottomSurface = Enum.SurfaceType.Smooth
		wallCollider.Material = Enum.Material.Neon
		wallCollider.TopSurface = Enum.SurfaceType.Smooth
		wallCollider.Color = Color3.fromRGB(255, 0, 0)
		wallCollider.CFrame = CFrame.new(Vector3.new(-727.0044, 109.2635, 98.9776)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		wallCollider.Parent = walls
		local wallCollider_2 = Instance.new("Part")
		wallCollider_2.Name = "WallCollider"
		wallCollider_2.Transparency = 1
		wallCollider_2.Anchored = true
		wallCollider_2.Size = Vector3.new(2.6824, 29.7859, 41.4639)
		wallCollider_2.BottomSurface = Enum.SurfaceType.Smooth
		wallCollider_2.Material = Enum.Material.Neon
		wallCollider_2.TopSurface = Enum.SurfaceType.Smooth
		wallCollider_2.Color = Color3.fromRGB(255, 0, 0)
		wallCollider_2.CFrame = CFrame.new(Vector3.new(-765.982, 109.2635, 98.9776)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		wallCollider_2.Parent = walls
		local wallCollider_3 = Instance.new("Part")
		wallCollider_3.Name = "WallCollider"
		wallCollider_3.Transparency = 1
		wallCollider_3.Anchored = true
		wallCollider_3.Size = Vector3.new(36.2953, 29.7859, 3.0813)
		wallCollider_3.BottomSurface = Enum.SurfaceType.Smooth
		wallCollider_3.Material = Enum.Material.Neon
		wallCollider_3.TopSurface = Enum.SurfaceType.Smooth
		wallCollider_3.Color = Color3.fromRGB(255, 0, 0)
		wallCollider_3.CFrame = CFrame.new(Vector3.new(-746.4932, 109.2635, 118.1689)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		wallCollider_3.Parent = walls
	end
	walls.Parent = elevator
	trapDoorR = Instance.new("Model")
	trapDoorR.Name = "TrapDoorR"
	do
		local wall_4 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16660675553", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
		wall_4.Name = "Wall"
		wall_4.Massless = true
		wall_4.Anchored = true
		wall_4.CanQuery = false
		wall_4.EnableFluidForces = false
		wall_4.Size = Vector3.new(8.093, 0.6089, 10.8)
		wall_4.Material = Enum.Material.Concrete
		wall_4.Color = Color3.fromRGB(107, 107, 107)
		wall_4.CFrame = CFrame.new(Vector3.new(-750.8335, 97.7912, 112.0799))
		wall_4.Parent = trapDoorR
		wall_5 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16660679149", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
		wall_5.Name = "Wall"
		wall_5.Massless = true
		wall_5.Anchored = true
		wall_5.CanQuery = false
		wall_5.EnableFluidForces = false
		wall_5.Size = Vector3.new(0.9824, 1.0076, 10.8087)
		wall_5.Material = Enum.Material.Metal
		wall_5.Color = Color3.fromRGB(99, 95, 98)
		wall_5.CFrame = CFrame.new(Vector3.new(-754.7966, 97.8103, 112.0799))
		wall_5.Parent = trapDoorR
		local wall_6 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16660679868", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
		wall_6.Name = "Wall"
		wall_6.Massless = true
		wall_6.Anchored = true
		wall_6.CanQuery = false
		wall_6.EnableFluidForces = false
		wall_6.Size = Vector3.new(3.7366, 0.1071, 3.8285)
		wall_6.Material = Enum.Material.SmoothPlastic
		wall_6.Color = Color3.fromRGB(181, 162, 69)
		wall_6.CFrame = CFrame.new(Vector3.new(-750.8942, 97.9238, 112.0615))
		do
			local decal_3 = Instance.new("Decal")
			decal_3.Texture = "rbxassetid://16660743178"
			decal_3.Face = Enum.NormalId.Top
			decal_3.Parent = wall_6
		end
		wall_6.Parent = trapDoorR
	end
	trapDoorR.Parent = elevator
	local monsterBlocker = Instance.new("Part")
	monsterBlocker.Name = "MonsterBlocker"
	monsterBlocker.CollisionGroup = "MonsterBlocker"
	monsterBlocker.Transparency = 1
	monsterBlocker.CastShadow = false
	monsterBlocker.Anchored = true
	monsterBlocker.EnableFluidForces = false
	monsterBlocker.Size = Vector3.new(40.4246, 25.5629, 38.6878)
	monsterBlocker.TopSurface = Enum.SurfaceType.Smooth
	monsterBlocker.BottomSurface = Enum.SurfaceType.Smooth
	monsterBlocker.Material = Enum.Material.ForceField
	monsterBlocker.Color = Color3.fromRGB(165, 63, 65)
	monsterBlocker.CFrame = CFrame.new(Vector3.new(-746.7511, 110.2, 97.9929)) * CFrame.fromEulerAnglesXYZ(0, math.rad(90), 0)
	monsterBlocker.Parent = elevator
	local lightModel = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16659790136", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
	lightModel.Name = "LightModel"
	lightModel.Anchored = true
	lightModel.Massless = true
	lightModel.EnableFluidForces = false
	lightModel.Size = Vector3.new(0.9686, 2.8668, 1.6839)
	lightModel.Material = Enum.Material.Neon
	lightModel.Color = Color3.fromRGB(0, 0, 0)
	lightModel.CFrame = CFrame.new(Vector3.new(-728.0255, 111.7452, 98.6727))
	do
		local particleCenter = Instance.new("Attachment")
		particleCenter.Name = "ParticleCenter"
		particleCenter.CFrame = CFrame.new(Vector3.yAxis * -0.1071)
		do
			local glow = Instance.new("ParticleEmitter")
			glow.Name = "Glow"
			glow.Texture = "rbxassetid://867619398"
			glow.Rate = 1.24
			glow.LightEmission = 1
			glow.ZOffset = 3.5
			glow.Enabled = false
			glow.LockedToPart = true
			glow.Size = NumberSequence.new(4)
			glow.Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 1), NumberSequenceKeypoint.new(0.5009, 0.5625), NumberSequenceKeypoint.new(1, 1)})
			glow.Speed = NumberRange.new(0)
			glow.Lifetime = NumberRange.new(3)
			glow.Color = ColorSequence.new(Color3.fromRGB(76, 99, 149), Color3.fromRGB(76, 99, 149))
			glow.Parent = particleCenter
		end
		particleCenter.Parent = lightModel
	end
	lightModel.Parent = elevator
	local lightModel2 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16659790136", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
	lightModel2.Name = "LightModel2"
	lightModel2.Anchored = true
	lightModel2.Massless = true
	lightModel2.EnableFluidForces = false
	lightModel2.Size = Vector3.new(0.9686, 2.8668, 1.6839)
	lightModel2.Material = Enum.Material.Neon
	lightModel2.Color = Color3.fromRGB(0, 0, 0)
	lightModel2.CFrame = CFrame.new(Vector3.new(-765.5117, 111.7452, 98.6727)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
	do
		local particleCenter_2 = Instance.new("Attachment")
		particleCenter_2.Name = "ParticleCenter"
		particleCenter_2.Axis = -Vector3.xAxis
		particleCenter_2.CFrame = CFrame.new(Vector3.yAxis * -0.1071) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
		do
			local glow_2 = Instance.new("ParticleEmitter")
			glow_2.Name = "Glow"
			glow_2.Texture = "rbxassetid://867619398"
			glow_2.Rate = 1.24
			glow_2.LightEmission = 1
			glow_2.ZOffset = 3.5
			glow_2.Enabled = false
			glow_2.LockedToPart = true
			glow_2.Size = NumberSequence.new(4)
			glow_2.Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 1), NumberSequenceKeypoint.new(0.5009, 0.5625), NumberSequenceKeypoint.new(1, 1)})
			glow_2.Speed = NumberRange.new(0)
			glow_2.Lifetime = NumberRange.new(3)
			glow_2.Color = ColorSequence.new(Color3.fromRGB(76, 99, 149), Color3.fromRGB(76, 99, 149))
			glow_2.Parent = particleCenter_2
		end
		particleCenter_2.Parent = lightModel2
	end
	lightModel2.Parent = elevator
	local base_2 = Instance.new("Part")
	base_2.Name = "Base"
	base_2.Transparency = 1
	base_2.EnableFluidForces = false
	base_2.Anchored = true
	base_2.Size = Vector3.new(40, 1, 40)
	base_2.BottomSurface = Enum.SurfaceType.Smooth
	base_2.TopSurface = Enum.SurfaceType.Smooth
	base_2.Material = Enum.Material.Concrete
	base_2.Color = Color3.fromRGB(248, 248, 248)
	base_2.CFrame = CFrame.new(Vector3.new(-746.7682, 96.9793, 98.6767)) * CFrame.fromEulerAnglesXYZ(0, math.rad(90), 0)
	base_2.Parent = elevator
	local wall_7 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16660178672", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Precise)
	wall_7.Name = "Wall"
	wall_7.Anchored = true
	wall_7.Massless = true
	wall_7.EnableFluidForces = false
	wall_7.Size = Vector3.new(38.168, 0.149, 1.952)
	wall_7.Material = Enum.Material.Concrete
	wall_7.Color = Color3.fromRGB(255, 241, 133)
	wall_7.CFrame = CFrame.new(Vector3.new(-746.7502, 97.5537, 79.0155))
	do
		local texture_4 = Instance.new("Texture")
		texture_4.Texture = "rbxassetid://6794283750"
		texture_4.Transparency = 0.8999
		texture_4.StudsPerTileV = 10
		texture_4.StudsPerTileU = 10
		texture_4.Face = Enum.NormalId.Back
		texture_4.Parent = wall_7
		local texture_5 = Instance.new("Texture")
		texture_5.Texture = "rbxassetid://6794283750"
		texture_5.Transparency = 0.8999
		texture_5.StudsPerTileV = 10
		texture_5.StudsPerTileU = 10
		texture_5.Face = Enum.NormalId.Left
		texture_5.Parent = wall_7
		local texture_6 = Instance.new("Texture")
		texture_6.Texture = "rbxassetid://6794283750"
		texture_6.StudsPerTileU = 10
		texture_6.StudsPerTileV = 10
		texture_6.Transparency = 0.8999
		texture_6.Parent = wall_7
		local texture_7 = Instance.new("Texture")
		texture_7.Texture = "rbxassetid://6794283750"
		texture_7.Transparency = 0.8999
		texture_7.StudsPerTileV = 10
		texture_7.StudsPerTileU = 10
		texture_7.Face = Enum.NormalId.Right
		texture_7.Parent = wall_7
		local texture_8 = Instance.new("Texture")
		texture_8.Texture = "rbxassetid://6794283750"
		texture_8.Transparency = 0.8999
		texture_8.StudsPerTileV = 10
		texture_8.StudsPerTileU = 10
		texture_8.Face = Enum.NormalId.Bottom
		texture_8.Parent = wall_7
		local texture_9 = Instance.new("Texture")
		texture_9.Texture = "rbxassetid://6794283750"
		texture_9.Transparency = 0.8999
		texture_9.StudsPerTileV = 10
		texture_9.StudsPerTileU = 10
		texture_9.Face = Enum.NormalId.Top
		texture_9.Parent = wall_7
	end
	wall_7.Parent = elevator
	local part_2 = Instance.new("Part")
	part_2.Anchored = true
	part_2.EnableFluidForces = false
	part_2.Size = Vector3.new(1.2638, 0.0434, 38.4248)
	part_2.Material = Enum.Material.DiamondPlate
	part_2.TopSurface = Enum.SurfaceType.Smooth
	part_2.BottomSurface = Enum.SurfaceType.Smooth
	part_2.Color = Color3.fromRGB(74, 72, 74)
	part_2.CFrame = CFrame.new(Vector3.new(-746.7485, 97.5985, 79.0515)) * CFrame.fromEulerAnglesXYZ(0, math.rad(90), 0)
	part_2.Parent = elevator
	local doorWheels = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16660437228", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
	doorWheels.Name = "DoorWheels"
	doorWheels.Anchored = true
	doorWheels.EnableFluidForces = false
	doorWheels.Massless = true
	doorWheels.CanCollide = false
	doorWheels.Size = Vector3.new(40.6399, 4.705, 4.705)
	doorWheels.Material = Enum.Material.DiamondPlate
	doorWheels.Color = Color3.fromRGB(99, 95, 98)
	doorWheels.CFrame = CFrame.new(Vector3.new(-746.6496, 121.8868, 79.742))
	doorWheels.Parent = elevator
	local part_3 = Instance.new("Part")
	part_3.Anchored = true
	part_3.EnableFluidForces = false
	part_3.Size = Vector3.new(39.9553, 2.4108, 40.1912)
	part_3.Material = Enum.Material.Concrete
	part_3.TopSurface = Enum.SurfaceType.Smooth
	part_3.BottomSurface = Enum.SurfaceType.Smooth
	part_3.Color = Color3.fromRGB(159, 161, 172)
	part_3.CFrame = CFrame.new(Vector3.new(-746.7727, 124.129, 98.792)) * CFrame.fromEulerAnglesXYZ(0, math.rad(90), 0)
	do
		local texture_10 = Instance.new("Texture")
		texture_10.Texture = "rbxassetid://6372755229"
		texture_10.Transparency = 0.8999
		texture_10.StudsPerTileU = 4.5536
		texture_10.StudsPerTileV = 4.5536
		texture_10.Face = Enum.NormalId.Bottom
		texture_10.Color3 = Color3.fromRGB(0, 0, 0)
		texture_10.Parent = part_3
		local texture_11 = Instance.new("Texture")
		texture_11.Texture = "rbxassetid://6372755229"
		texture_11.Transparency = 0.8999
		texture_11.StudsPerTileU = 4.5536
		texture_11.StudsPerTileV = 4.5536
		texture_11.Face = Enum.NormalId.Top
		texture_11.Color3 = Color3.fromRGB(0, 0, 0)
		texture_11.Parent = part_3
	end
	part_3.Parent = elevator
	local edge = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://95939238927491", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Automatic)
	edge.Name = "Edge"
	edge.Anchored = true
	edge.Size = Vector3.new(18.33, 0.4101, 12.3099)
	edge.Color = Color3.fromRGB(255, 241, 133)
	edge.CFrame = CFrame.new(Vector3.new(-746.7345, 97.3136, 111.7047)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
	edge.PivotOffset = CFrame.new(Vector3.new(0.005, -0.3441, 13.2403))
	do
		local texture_12 = Instance.new("Texture")
		texture_12.Texture = "rbxassetid://6794283750"
		texture_12.Transparency = 0.8999
		texture_12.StudsPerTileV = 9
		texture_12.StudsPerTileU = 9
		texture_12.Face = Enum.NormalId.Top
		texture_12.Parent = edge
	end
	edge.Parent = elevator
	local light_2 = Instance.new("Part")
	light_2.Name = "Light"
	light_2.Transparency = 1
	light_2.CanQuery = false
	light_2.CanTouch = false
	light_2.Anchored = true
	light_2.CanCollide = false
	light_2.EnableFluidForces = false
	light_2.Size = Vector3.new(6.5525, 0.7571, 2)
	light_2.BottomSurface = Enum.SurfaceType.Smooth
	light_2.Material = Enum.Material.SmoothPlastic
	light_2.TopSurface = Enum.SurfaceType.Smooth
	light_2.Color = Color3.fromRGB(27, 42, 53)
	light_2.CFrame = CFrame.new(Vector3.new(-757.0225, 113.2773, 98.4657)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
	do
		local pointLight_3 = Instance.new("PointLight")
		pointLight_3.Range = 25
		pointLight_3.Enabled = false
		pointLight_3.Shadows = true
		pointLight_3.Color = Color3.fromRGB(167, 195, 234)
		pointLight_3.Parent = light_2
	end
	light_2.Parent = elevator
	local light2 = Instance.new("Part")
	light2.Name = "Light2"
	light2.Transparency = 1
	light2.EnableFluidForces = false
	light2.Anchored = true
	light2.CanCollide = false
	light2.Size = Vector3.new(6.5525, 0.7571, 2)
	light2.Material = Enum.Material.SmoothPlastic
	light2.BottomSurface = Enum.SurfaceType.Smooth
	light2.TopSurface = Enum.SurfaceType.Smooth
	light2.Color = Color3.fromRGB(27, 42, 53)
	light2.CFrame = CFrame.new(Vector3.new(-738.4023, 113.2773, 98.4657)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
	do
		local pointLight_4 = Instance.new("PointLight")
		pointLight_4.Range = 25
		pointLight_4.Enabled = false
		pointLight_4.Shadows = true
		pointLight_4.Color = Color3.fromRGB(167, 195, 234)
		pointLight_4.Parent = light2
	end
	light2.Parent = elevator
	local wall_8 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16660676918", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
	wall_8.Name = "Wall"
	wall_8.Anchored = true
	wall_8.Massless = true
	wall_8.EnableFluidForces = false
	wall_8.Size = Vector3.new(0.6194, 1.0185, 11.2786)
	wall_8.Material = Enum.Material.DiamondPlate
	wall_8.Color = Color3.fromRGB(74, 74, 76)
	wall_8.CFrame = CFrame.new(Vector3.new(-738.7875, 97.6184, 112.0797)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
	wall_8.Parent = elevator
	local wall_9 = game:GetService("InsertService"):CreateMeshPartAsync("rbxassetid://16660676918", Enum.CollisionFidelity.Box, Enum.RenderFidelity.Performance)
	wall_9.Name = "Wall"
	wall_9.Anchored = true
	wall_9.Massless = true
	wall_9.EnableFluidForces = false
	wall_9.Size = Vector3.new(0.6194, 1.0185, 11.2786)
	wall_9.Material = Enum.Material.DiamondPlate
	wall_9.Color = Color3.fromRGB(74, 74, 76)
	wall_9.CFrame = CFrame.new(Vector3.new(-754.7966, 97.6184, 112.0797))
	wall_9.Parent = elevator
	local elevatorSounds = Instance.new("Part")
	elevatorSounds.Name = "ElevatorSounds"
	elevatorSounds.Transparency = 1
	elevatorSounds.CanQuery = false
	elevatorSounds.CanTouch = false
	elevatorSounds.Anchored = true
	elevatorSounds.EnableFluidForces = false
	elevatorSounds.CanCollide = false
	elevatorSounds.Size = Vector3.new(3.3085, 0.8271, 1.6542)
	elevatorSounds.BottomSurface = Enum.SurfaceType.Smooth
	elevatorSounds.TopSurface = Enum.SurfaceType.Smooth
	elevatorSounds.CFrame = CFrame.new(Vector3.new(-746.7682, 123.3633, 98.4823)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
	do
		local buzz_2 = Instance.new("Sound")
		buzz_2.SoundId = "rbxassetid://9112889325"
		buzz_2.Name = "Buzz"
		buzz_2.RollOffMaxDistance = 50
		buzz_2.Volume = 0.75
		buzz_2.Looped = true
		buzz_2.RollOffMode = Enum.RollOffMode.Linear
		buzz_2.AudioContent = Content.fromUri("rbxassetid://9112889325")
		buzz_2.Parent = elevatorSounds
	end
	elevatorSounds.Parent = elevator
	local doorHitbox = Instance.new("Part")
	doorHitbox.Name = "DoorHitbox"
	doorHitbox.Transparency = 1
	doorHitbox.EnableFluidForces = false
	doorHitbox.Anchored = true
	doorHitbox.Size = Vector3.new(40.3976, 26.7695, 2.0994)
	doorHitbox.BottomSurface = Enum.SurfaceType.Smooth
	doorHitbox.TopSurface = Enum.SurfaceType.Smooth
	doorHitbox.Material = Enum.Material.Concrete
	doorHitbox.Color = Color3.fromRGB(107, 107, 107)
	doorHitbox.CFrame = CFrame.new(Vector3.new(-747.1088, 110.6912, 78.9674))
	doorHitbox.Parent = elevator
	local invisWall = Instance.new("Part")
	invisWall.Name = "InvisWall"
	invisWall.Transparency = 1
	invisWall.EnableFluidForces = false
	invisWall.Anchored = true
	invisWall.Size = Vector3.new(18.2767, 28.3899, 13.5725)
	invisWall.BottomSurface = Enum.SurfaceType.Smooth
	invisWall.TopSurface = Enum.SurfaceType.Smooth
	invisWall.Material = Enum.Material.DiamondPlate
	invisWall.Color = Color3.fromRGB(74, 72, 74)
	invisWall.CFrame = CFrame.new(Vector3.new(-746.7712, 108.1553, 112.3867)) * CFrame.fromEulerAnglesXYZ(math.rad(-180), 0, math.rad(-180))
	invisWall.Parent = elevator
	elevator_2 = Instance.new("Part")
	elevator_2.Name = "Elevator"
	elevator_2.Transparency = 1
	elevator_2.EnableFluidForces = false
	elevator_2.Anchored = true
	elevator_2.Size = Vector3.new(1.2332, 0.032, 1.2332)
	elevator_2.TopSurface = Enum.SurfaceType.Smooth
	elevator_2.BottomSurface = Enum.SurfaceType.Smooth
	elevator_2.CFrame = CFrame.new(Vector3.new(-746.7682, 96.9695, 98.4713))
	elevator_2.Parent = elevator
	local elevatorHitBox = Instance.new("Part")
	elevatorHitBox.Name = "ElevatorHitBox"
	elevatorHitBox.Transparency = 1
	elevatorHitBox.CastShadow = false
	elevatorHitBox.EnableFluidForces = false
	elevatorHitBox.Anchored = true
	elevatorHitBox.CanCollide = false
	elevatorHitBox.Size = Vector3.new(37.671, 25.828, 38.7868)
	elevatorHitBox.TopSurface = Enum.SurfaceType.Smooth
	elevatorHitBox.BottomSurface = Enum.SurfaceType.Smooth
	elevatorHitBox.Material = Enum.Material.ForceField
	elevatorHitBox.Color = Color3.fromRGB(165, 63, 65)
	elevatorHitBox.CFrame = CFrame.new(Vector3.new(-746.7512, 110.2612, 99.2238)) * CFrame.fromEulerAnglesXYZ(0, math.rad(90), 0)
	elevatorHitBox.Parent = elevator
end

elevator.PrimaryPart = elevator_2
elevatorDoor.PrimaryPart = giantDoorBase
trapDoorL.PrimaryPart = wall_2
light.Value = surfaceLight
static.Value = staticFrame
mastery.Value = masteryFrame
dandyStatic.Value = dandyStaticPopup
pointLight.Value = pointLight_2
blackOverlay.Value = blackOverlay_2
trapDoorR.PrimaryPart = wall_5

return elevator
